import { auth } from '@/lib/auth'
import { getWikiEntry } from '@/actions/wiki'
import { notFound } from 'next/navigation'
import Link from 'next/link'

export default async function WikiEntryPage({
  params,
}: {
  params: Promise<{ campaignId: string; entryId: string }>
}) {
  const { campaignId, entryId } = await params
  const session = await auth()
  const entry = await getWikiEntry(entryId, session!.user.id)

  if (!entry) {
    notFound()
  }

  return (
    <div className="max-w-4xl mx-auto space-y-6">
      <div>
        <Link
          href={`/campaigns/${campaignId}/wiki`}
          className="text-purple-300 hover:text-purple-200 text-sm mb-2 inline-block"
        >
          ← Back to Wiki
        </Link>
      </div>

      <div className="bg-white/10 backdrop-blur-sm rounded-lg border border-purple-500/30 p-8">
        <h1 className="text-3xl font-bold text-white mb-4">{entry.title}</h1>

        <div className="flex flex-wrap gap-2 mb-6">
          <span className="text-sm bg-purple-500/20 text-purple-300 px-3 py-1 rounded">
            {entry.type.replace('_', ' ')}
          </span>
          {entry.tags.map((tag) => (
            <span
              key={tag}
              className="text-sm bg-white/10 text-slate-300 px-3 py-1 rounded"
            >
              {tag}
            </span>
          ))}
          {entry.isAutoGenerated && (
            <span className="text-sm bg-blue-500/20 text-blue-300 px-3 py-1 rounded">
              Auto-generated
            </span>
          )}
        </div>

        {entry.audioFile && (
          <div className="mb-6 p-4 bg-black/30 rounded-lg">
            <p className="text-sm text-slate-400">
              Source: <span className="text-slate-300">{entry.audioFile.filename}</span>
            </p>
          </div>
        )}

        <div className="prose prose-invert max-w-none">
          <div className="text-slate-300 whitespace-pre-wrap leading-relaxed">
            {entry.content}
          </div>
        </div>

        {entry.children.length > 0 && (
          <div className="mt-8">
            <h2 className="text-xl font-bold text-white mb-4">Related Entries</h2>
            <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
              {entry.children.map((child) => (
                <Link
                  key={child.id}
                  href={`/campaigns/${campaignId}/wiki/${child.id}`}
                  className="bg-white/10 rounded-lg p-4 hover:bg-white/20 transition-colors"
                >
                  <h3 className="text-white font-semibold">{child.title}</h3>
                  {child.excerpt && (
                    <p className="text-sm text-slate-400 mt-1 line-clamp-2">
                      {child.excerpt}
                    </p>
                  )}
                </Link>
              ))}
            </div>
          </div>
        )}

        <div className="mt-6 pt-6 border-t border-purple-500/30 text-sm text-slate-400">
          <p>
            Created: {new Date(entry.createdAt).toLocaleDateString()}
            {' • '}
            Updated: {new Date(entry.updatedAt).toLocaleDateString()}
          </p>
        </div>
      </div>
    </div>
  )
}
