import { auth } from '@/lib/auth'
import { getCampaign } from '@/actions/campaigns'
import { getWikiTree, getWikiEntry } from '@/actions/wiki'
import { getCampaignCharacterSheets } from '@/actions/character-sheet'
import { getCampaignAccess } from '@/lib/permissions'
import { acceptPendingInvites } from '@/actions/campaign-members'
import { notFound } from 'next/navigation'
import WikiPageLayout from '@/components/wiki/WikiPageLayout'
import PlayerCampaignView from '@/components/player/PlayerCampaignView'

export default async function CampaignPage({
  params,
  searchParams,
}: {
  params: Promise<{ campaignId: string }>
  searchParams: Promise<{ entry?: string }>
}) {
  const { campaignId } = await params
  const { entry: entryParam } = await searchParams
  const session = await auth()
  const userId = session!.user.id
  const userEmail = session!.user.email!

  // Accept any pending invites for this user on page load
  await acceptPendingInvites(userId, userEmail)

  const campaign = await getCampaign(campaignId, userId)
  if (!campaign) {
    notFound()
  }

  const access = await getCampaignAccess(campaignId, userId)
  if (!access) {
    notFound()
  }

  // === PLAYER VIEW ===
  if (access.role === 'PLAYER') {
    const allSheets = await getCampaignCharacterSheets(campaignId, userId)
    const mySheet = allSheets.find((s) => s.assignedPlayerId === userId) ?? null

    return (
      <PlayerCampaignView
        campaignId={campaignId}
        userId={userId}
        campaign={{ name: campaign.name, description: campaign.description }}
        allSheets={allSheets.map((s) => ({
          id: s.id,
          data: s.data as any,
          assignedPlayerId: s.assignedPlayerId,
          assignedPlayer: s.assignedPlayer,
          wikiEntry: s.wikiEntry,
        }))}
        mySheetId={mySheet?.id ?? null}
      />
    )
  }

  // === DM VIEW ===
  const [wikiTree, characterSheets] = await Promise.all([
    getWikiTree(campaignId, userId),
    getCampaignCharacterSheets(campaignId, userId),
  ])

  // Determine which entry to show
  let activeEntry = null
  let activeEntryId = entryParam

  if (!activeEntryId && wikiTree.length > 0) {
    // Default to latest SESSION_RECAP, or first entry
    const sessionRecap = wikiTree.find((e) => e.type === 'SESSION_RECAP')
    activeEntryId = sessionRecap?.id || wikiTree[0].id
  }

  if (activeEntryId) {
    try {
      activeEntry = await getWikiEntry(activeEntryId, userId)
    } catch {
      // Entry not found, show empty state
    }
  }

  return (
    <WikiPageLayout
      campaignId={campaignId}
      userId={userId}
      campaign={{
        name: campaign.name,
        description: campaign.description,
        language: campaign.language,
      }}
      wikiTree={wikiTree}
      characterSheets={characterSheets.map((s) => ({
        id: s.id,
        assignedPlayerId: s.assignedPlayerId,
        wikiEntry: s.wikiEntry,
      }))}
      activeEntry={
        activeEntry
          ? {
              id: activeEntry.id,
              title: activeEntry.title,
              type: activeEntry.type,
              content: activeEntry.content,
              tags: activeEntry.tags,
              isAutoGenerated: activeEntry.isAutoGenerated,
              audioFile: activeEntry.audioFile,
              children: activeEntry.children.map((c) => ({
                id: c.id,
                title: c.title,
                excerpt: c.excerpt,
              })),
              createdAt: activeEntry.createdAt,
              updatedAt: activeEntry.updatedAt,
              characterSheet: activeEntry.characterSheet
                ? {
                    id: activeEntry.characterSheet.id,
                    data: activeEntry.characterSheet.data as unknown as import('@/types/character-sheet').CharacterSheetData,
                    pdfBlobUrl: activeEntry.characterSheet.pdfBlobUrl,
                  }
                : null,
            }
          : null
      }
    />
  )
}
