'use client'

import { useState, useCallback, useEffect } from 'react'
import { WikiEntryType } from '@prisma/client'
import { ScrollText, Upload, Plus, ArrowLeft } from 'lucide-react'
import { cn } from '@/lib/utils'
import WikiEntryEditor from './WikiEntryEditor'
import AudioUploadDialog from './AudioUploadDialog'
import CreateSessionDialog from './CreateSessionDialog'
import { useI18n } from '@/lib/i18n-context'
import { Button } from '@/components/ui/button'
import type { CharacterSheetData } from '@/types/character-sheet'

interface WikiTreeEntry {
  id: string
  title: string
  slug: string
  type: WikiEntryType
  parentId: string | null
  createdAt: Date
}

interface ActiveEntry {
  id: string
  title: string
  type: WikiEntryType
  content: string
  tags: string[]
  isAutoGenerated: boolean
  audioFile: { id: string; filename: string } | null
  children: { id: string; title: string; excerpt: string | null }[]
  createdAt: Date
  updatedAt: Date
  characterSheet?: {
    id: string
    data: CharacterSheetData
    pdfBlobUrl: string | null
  } | null
}

function formatDate(date: Date, format: string): string {
  const d = new Date(date)
  const day = String(d.getDate()).padStart(2, '0')
  const month = String(d.getMonth() + 1).padStart(2, '0')
  const yearFull = String(d.getFullYear())
  const yearShort = yearFull.slice(-2)

  switch (format) {
    case 'MM/DD/YY':
      return `${month}/${day}/${yearShort}`
    case 'YYYY-MM-DD':
      return `${yearFull}-${month}-${day}`
    case 'DD.MM.YY':
    default:
      return `${day}.${month}.${yearShort}`
  }
}

interface SessionsViewProps {
  campaignId: string
  userId: string
  entries: WikiTreeEntry[]
  activeEntry: ActiveEntry | null
  dateFormat: string
  isLocked?: boolean
  onUnsavedChange: (isDirty: boolean) => void
  onNavigate: (href: string) => void
}

export default function SessionsView({
  campaignId,
  userId,
  entries,
  activeEntry,
  dateFormat,
  isLocked,
  onUnsavedChange,
  onNavigate,
}: SessionsViewProps) {
  const { t } = useI18n()
  const [uploadOpen, setUploadOpen] = useState(false)
  const [createSessionOpen, setCreateSessionOpen] = useState(false)
  const [mobileShowDetail, setMobileShowDetail] = useState(!!activeEntry)
  const [sidebarWidth, setSidebarWidth] = useState(280)
  const [isDesktop, setIsDesktop] = useState(true)

  useEffect(() => {
    const check = () => setIsDesktop(window.innerWidth >= 768)
    check()
    window.addEventListener('resize', check)
    return () => window.removeEventListener('resize', check)
  }, [])

  const handleSidebarResizeMouseDown = useCallback((e: React.MouseEvent) => {
    e.preventDefault()
    const startX = e.clientX
    const startWidth = sidebarWidth
    const handleMouseMove = (e: MouseEvent) => {
      setSidebarWidth(Math.max(180, Math.min(480, startWidth + (e.clientX - startX))))
    }
    const handleMouseUp = () => {
      document.removeEventListener('mousemove', handleMouseMove)
      document.removeEventListener('mouseup', handleMouseUp)
    }
    document.addEventListener('mousemove', handleMouseMove)
    document.addEventListener('mouseup', handleMouseUp)
  }, [sidebarWidth])

  const sessions = entries
    .filter((e) => e.type === 'SESSION_RECAP')
    .sort((a, b) => new Date(b.createdAt).getTime() - new Date(a.createdAt).getTime())

  const handleSelectEntry = useCallback((id: string) => {
    onNavigate(`/campaigns/${campaignId}?tab=sessions&entry=${id}`)
    setMobileShowDetail(true)
  }, [campaignId, onNavigate])

  const handleMobileBack = useCallback(() => {
    setMobileShowDetail(false)
  }, [])

  return (
    <div className="flex flex-1 overflow-hidden">
      {/* List panel */}
      <div
        style={isDesktop ? { width: sidebarWidth } : undefined}
        className={cn(
          'flex-shrink-0 border-r bg-card flex flex-col overflow-hidden',
          mobileShowDetail ? 'hidden md:flex' : 'flex w-full md:w-auto'
        )}
      >
        {/* Actions */}
        {!isLocked && (
          <div className="flex flex-col gap-1.5 p-2 border-b">
            <Button size="sm" onClick={() => setCreateSessionOpen(true)} className="w-full">
              <Plus className="w-3.5 h-3.5 mr-1.5" />
              {t('sidebar.newSession')}
            </Button>
            <Button size="sm" variant="outline" onClick={() => setUploadOpen(true)} className="w-full">
              <Upload className="w-3.5 h-3.5 mr-1.5" />
              {t('sidebar.uploadAudio')}
            </Button>
          </div>
        )}

        {/* Sessions list */}
        <nav className="flex-1 overflow-y-auto p-2">
          {sessions.length === 0 ? (
            <div className="text-center py-8 px-4">
              <ScrollText className="w-8 h-8 text-muted-foreground mx-auto mb-3 opacity-50" />
              <p className="text-sm font-medium mb-1">{t('empty.sessions')}</p>
              <p className="text-xs text-muted-foreground">{t('empty.sessionsHint')}</p>
            </div>
          ) : (
            sessions.map((entry) => (
              <button
                key={entry.id}
                onClick={() => handleSelectEntry(entry.id)}
                className={`w-full text-left px-3 py-2 text-sm rounded-lg truncate transition-all mb-0.5 ${
                  entry.id === activeEntry?.id
                    ? 'bg-primary/10 text-primary font-medium'
                    : 'text-muted-foreground hover:text-foreground hover:bg-accent'
                }`}
              >
                <span className="text-xs text-muted-foreground">{formatDate(entry.createdAt, dateFormat)}</span>
                <span className="ml-1.5">{entry.title}</span>
              </button>
            ))
          )}
        </nav>
      </div>

      {/* Resize handle */}
      <div
        onMouseDown={handleSidebarResizeMouseDown}
        className="w-1 flex-shrink-0 bg-border hover:bg-primary/50 cursor-col-resize transition-colors select-none hidden md:block"
      />

      {/* Detail panel */}
      <div className={`flex-1 flex flex-col overflow-hidden ${!mobileShowDetail ? 'hidden md:flex' : 'flex'}`}>
        {/* Mobile back button */}
        {mobileShowDetail && (
          <div className="md:hidden border-b px-3 py-2">
            <Button variant="ghost" size="sm" onClick={handleMobileBack}>
              <ArrowLeft className="w-4 h-4 mr-1.5" />
              {t('tabs.sessions')}
            </Button>
          </div>
        )}

        {activeEntry ? (
          <WikiEntryEditor
            campaignId={campaignId}
            userId={userId}
            entry={activeEntry}
            onUnsavedChange={onUnsavedChange}
            isReadOnly={isLocked}
          />
        ) : (
          <div className="flex-1 flex items-center justify-center px-4">
            <div className="text-center">
              <ScrollText className="w-12 h-12 text-muted-foreground/30 mx-auto mb-3" />
              <p className="text-muted-foreground text-sm">
                {sessions.length === 0 ? t('empty.sessions') : t('empty.selectSession')}
              </p>
            </div>
          </div>
        )}
      </div>

      {/* Dialogs */}
      <AudioUploadDialog
        campaignId={campaignId}
        isOpen={uploadOpen}
        onClose={() => setUploadOpen(false)}
      />
      <CreateSessionDialog
        campaignId={campaignId}
        userId={userId}
        isOpen={createSessionOpen}
        onClose={() => setCreateSessionOpen(false)}
      />
    </div>
  )
}
