'use client'

import { useState, useCallback, useEffect } from 'react'
import { WikiEntryType } from '@prisma/client'
import { ScrollText, Upload, Plus, ArrowLeft, Clock, FileText } from 'lucide-react'
import { cn } from '@/lib/utils'
import WikiEntryEditor from './WikiEntryEditor'
import AudioUploadDialog from './AudioUploadDialog'
import CreateSessionDialog from './CreateSessionDialog'
import { useI18n } from '@/lib/i18n-context'
import { Button } from '@/components/ui/button'
import type { CharacterSheetData } from '@/types/character-sheet'

interface WikiTreeEntry {
  id: string
  title: string
  slug: string
  type: WikiEntryType
  parentId: string | null
  createdAt: Date
}

interface ActiveEntry {
  id: string
  title: string
  type: WikiEntryType
  content: string
  tags: string[]
  isAutoGenerated: boolean
  audioFile: { id: string; filename: string } | null
  children: { id: string; title: string; excerpt: string | null }[]
  createdAt: Date
  updatedAt: Date
  characterSheet?: {
    id: string
    data: CharacterSheetData
    pdfBlobUrl: string | null
  } | null
}

function formatDate(date: Date, format: string): string {
  const d = new Date(date)
  const day = String(d.getDate()).padStart(2, '0')
  const month = String(d.getMonth() + 1).padStart(2, '0')
  const yearFull = String(d.getFullYear())
  const yearShort = yearFull.slice(-2)

  switch (format) {
    case 'MM/DD/YY':
      return `${month}/${day}/${yearShort}`
    case 'YYYY-MM-DD':
      return `${yearFull}-${month}-${day}`
    case 'DD.MM.YY':
    default:
      return `${day}.${month}.${yearShort}`
  }
}

function formatDateLong(date: Date): string {
  return new Date(date).toLocaleDateString('en-US', {
    year: 'numeric',
    month: 'long',
    day: 'numeric',
  })
}

interface SessionsViewProps {
  campaignId: string
  userId: string
  entries: WikiTreeEntry[]
  activeEntry: ActiveEntry | null
  dateFormat: string
  isLocked?: boolean
  isReadOnly?: boolean
  onUnsavedChange: (isDirty: boolean) => void
  onNavigate: (href: string) => void
}

export default function SessionsView({
  campaignId,
  userId,
  entries,
  activeEntry,
  dateFormat,
  isLocked,
  isReadOnly,
  onUnsavedChange,
  onNavigate,
}: SessionsViewProps) {
  const { t } = useI18n()
  const [uploadOpen, setUploadOpen] = useState(false)
  const [createSessionOpen, setCreateSessionOpen] = useState(false)
  const [mobileShowDetail, setMobileShowDetail] = useState(!!activeEntry)

  const sessions = entries
    .filter((e) => e.type === 'SESSION_RECAP')
    .sort((a, b) => new Date(b.createdAt).getTime() - new Date(a.createdAt).getTime())

  const handleSelectEntry = useCallback((id: string) => {
    onNavigate(`/campaigns/${campaignId}?view=sessions&entry=${id}`)
    setMobileShowDetail(true)
  }, [campaignId, onNavigate])

  const handleMobileBack = useCallback(() => {
    setMobileShowDetail(false)
  }, [])

  return (
    <div className="flex-1 overflow-y-auto">
      <div className="p-4 md:p-8 max-w-6xl mx-auto flex flex-col h-full min-h-0">
        {/* Header */}
        <header className="flex flex-col sm:flex-row sm:items-center justify-between gap-4 mb-6 md:mb-8 flex-shrink-0">
          <div>
            <h1 className="text-2xl md:text-4xl font-semibold text-foreground mb-1 md:mb-2">
              Sessions &amp; Audio
            </h1>
            <p className="text-muted-foreground text-sm md:text-base">
              Upload session recordings to generate transcripts, summaries, and wiki updates.
            </p>
          </div>
          {!isLocked && !isReadOnly && (
            <div className="flex gap-2 flex-shrink-0">
              <Button
                variant="outline"
                onClick={() => setCreateSessionOpen(true)}
                className="rounded-xl"
              >
                <Plus className="w-4 h-4 mr-2" />
                {t('sidebar.newSession')}
              </Button>
              <Button
                onClick={() => setUploadOpen(true)}
                className="rounded-xl"
              >
                <Upload className="w-4 h-4 mr-2" />
                {t('sidebar.uploadAudio')}
              </Button>
            </div>
          )}
        </header>

        {/* Content Grid */}
        <div className="grid grid-cols-1 lg:grid-cols-3 gap-4 md:gap-8 flex-1 min-h-0">
          {/* Left: Session List */}
          <div
            className={cn(
              'lg:col-span-1 border border-border bg-card rounded-2xl overflow-hidden flex flex-col',
              mobileShowDetail ? 'hidden lg:flex' : 'flex'
            )}
          >
            <div className="p-4 border-b border-border bg-card">
              <h2 className="font-medium text-foreground text-sm">Past Sessions</h2>
            </div>
            <div className="flex-1 overflow-y-auto">
              {sessions.length === 0 ? (
                <div className="text-center py-12 px-4">
                  <ScrollText className="w-8 h-8 text-muted-foreground mx-auto mb-3 opacity-50" />
                  <p className="text-sm font-medium mb-1">{t('empty.sessions')}</p>
                  <p className="text-xs text-muted-foreground">{t('empty.sessionsHint')}</p>
                </div>
              ) : (
                sessions.map((entry, i) => (
                  <button
                    key={entry.id}
                    onClick={() => handleSelectEntry(entry.id)}
                    className={cn(
                      'w-full text-left p-4 border-b border-border cursor-pointer transition-colors',
                      entry.id === activeEntry?.id
                        ? 'bg-accent border-l-2 border-l-primary'
                        : 'hover:bg-accent'
                    )}
                  >
                    <div className="flex justify-between items-start mb-1">
                      <h3 className="font-medium text-foreground text-sm truncate pr-2">
                        {entry.title}
                      </h3>
                      <span className="text-xs text-muted-foreground whitespace-nowrap">
                        {formatDate(entry.createdAt, dateFormat)}
                      </span>
                    </div>
                    <div className="flex items-center gap-3 text-xs text-muted-foreground mt-1">
                      <span className="flex items-center gap-1 text-emerald-600 dark:text-emerald-400">
                        <FileText className="w-3 h-3" /> Processed
                      </span>
                    </div>
                  </button>
                ))
              )}
            </div>
          </div>

          {/* Right: Session Detail */}
          <div
            className={cn(
              'lg:col-span-2 border border-border bg-card rounded-2xl flex flex-col overflow-hidden',
              !mobileShowDetail ? 'hidden lg:flex' : 'flex'
            )}
          >
            {/* Mobile back button */}
            {mobileShowDetail && (
              <div className="lg:hidden border-b border-border px-3 py-2">
                <Button variant="ghost" size="sm" onClick={handleMobileBack}>
                  <ArrowLeft className="w-4 h-4 mr-1.5" />
                  {t('tabs.sessions')}
                </Button>
              </div>
            )}

            {activeEntry ? (
              <WikiEntryEditor
                campaignId={campaignId}
                userId={userId}
                entry={activeEntry}
                onUnsavedChange={onUnsavedChange}
                isReadOnly={isLocked || isReadOnly}
              />
            ) : (
              <div className="flex-1 flex items-center justify-center px-4">
                <div className="text-center">
                  <ScrollText className="w-12 h-12 text-muted-foreground/30 mx-auto mb-3" />
                  <p className="text-muted-foreground text-sm">
                    {sessions.length === 0 ? t('empty.sessions') : t('empty.selectSession')}
                  </p>
                </div>
              </div>
            )}
          </div>
        </div>
      </div>

      {/* Dialogs */}
      {!isReadOnly && (
        <>
          <AudioUploadDialog
            campaignId={campaignId}
            isOpen={uploadOpen}
            onClose={() => setUploadOpen(false)}
          />
          <CreateSessionDialog
            campaignId={campaignId}
            userId={userId}
            isOpen={createSessionOpen}
            onClose={() => setCreateSessionOpen(false)}
          />
        </>
      )}
    </div>
  )
}
