'use client'

import { useState, useEffect } from 'react'
import { useRouter } from 'next/navigation'
import { updateWikiEntry, deleteWikiEntry } from '@/actions/wiki'
import { WikiEntryType } from '@prisma/client'
import { Pencil, Trash2, Save, X, Sparkles, Music } from 'lucide-react'
import { useI18n } from '@/lib/i18n-context'

const typeColors: Record<WikiEntryType, string> = {
  SESSION_RECAP: 'bg-accent-purple/20 text-accent-purple-light',
  CHARACTER: 'bg-blue-500/20 text-blue-300',
  LOCATION: 'bg-emerald-500/20 text-emerald-300',
  EVENT: 'bg-red-500/20 text-red-300',
  ITEM: 'bg-amber-500/20 text-amber-300',
  NPC: 'bg-pink-500/20 text-pink-300',
  FACTION: 'bg-cyan-500/20 text-cyan-300',
  LORE: 'bg-indigo-500/20 text-indigo-300',
  QUEST: 'bg-orange-500/20 text-orange-300',
  OTHER: 'bg-gray-500/20 text-gray-300',
}

interface WikiEntryEditorProps {
  campaignId: string
  userId: string
  entry: {
    id: string
    title: string
    type: WikiEntryType
    content: string
    tags: string[]
    isAutoGenerated: boolean
    audioFile: { id: string; filename: string } | null
    children: { id: string; title: string; excerpt: string | null }[]
    createdAt: Date
    updatedAt: Date
  }
}

export default function WikiEntryEditor({ campaignId, userId, entry }: WikiEntryEditorProps) {
  const router = useRouter()
  const [editing, setEditing] = useState(false)
  const [title, setTitle] = useState(entry.title)
  const [content, setContent] = useState(entry.content)
  const [saving, setSaving] = useState(false)
  const [deleting, setDeleting] = useState(false)
  const { t } = useI18n()

  useEffect(() => {
    setEditing(false)
    setTitle(entry.title)
    setContent(entry.content)
  }, [entry.id, entry.title, entry.content])

  const handleSave = async () => {
    setSaving(true)
    try {
      await updateWikiEntry(entry.id, userId, { title, content })
      setEditing(false)
      router.refresh()
    } catch (err) {
      alert(err instanceof Error ? err.message : 'Failed to save')
    } finally {
      setSaving(false)
    }
  }

  const handleDelete = async () => {
    if (!confirm('Are you sure you want to delete this entry? This cannot be undone.')) return
    setDeleting(true)
    try {
      await deleteWikiEntry(entry.id, userId)
      router.push(`/campaigns/${campaignId}`)
      router.refresh()
    } catch (err) {
      alert(err instanceof Error ? err.message : 'Failed to delete')
      setDeleting(false)
    }
  }

  return (
    <div className="flex-1 overflow-y-auto p-4 sm:p-6 lg:p-8">
      <div className="max-w-4xl">
        {/* Header */}
        <div className="mb-6">
          {editing ? (
            <input
              type="text"
              value={title}
              onChange={(e) => setTitle(e.target.value)}
              className="text-2xl sm:text-3xl font-bold text-text-primary bg-transparent border-b border-border-theme focus:border-accent-purple focus:outline-none w-full pb-1"
            />
          ) : (
            <h1 className="text-2xl sm:text-3xl font-bold text-text-primary text-glow">{entry.title}</h1>
          )}

          <div className="flex flex-wrap items-center gap-2 mt-3">
            <span className={`text-xs font-medium px-3 py-1 rounded-full ${typeColors[entry.type]}`}>
              {t(`wiki.typeSingle.${entry.type}`)}
            </span>
            {entry.tags.map((tag) => (
              <span
                key={tag}
                className="text-xs bg-white/5 text-text-muted px-3 py-1 rounded-full border border-border-theme"
              >
                {tag}
              </span>
            ))}
            {entry.isAutoGenerated && (
              <span className="text-xs bg-accent-purple/10 text-accent-purple-light px-3 py-1 rounded-full flex items-center gap-1">
                <Sparkles className="w-3 h-3" />
                {t('wiki.autoGenerated')}
              </span>
            )}
          </div>
        </div>

        {/* Source audio */}
        {entry.audioFile && (
          <div className="mb-6 p-3 rounded-lg bg-surface-elevated border border-border-theme flex items-center gap-2">
            <Music className="w-4 h-4 text-text-muted" />
            <p className="text-sm text-text-muted">
              {t('wiki.source')}: <span className="text-text-secondary">{entry.audioFile.filename}</span>
            </p>
          </div>
        )}

        {/* Content */}
        {editing ? (
          <textarea
            value={content}
            onChange={(e) => setContent(e.target.value)}
            rows={20}
            className="w-full px-4 py-3 rounded-lg input-dark leading-relaxed resize-y text-sm sm:text-base"
          />
        ) : (
          <div className="text-text-secondary whitespace-pre-wrap leading-relaxed text-sm sm:text-base">
            {entry.content}
          </div>
        )}

        {/* Related entries */}
        {!editing && entry.children.length > 0 && (
          <div className="mt-8">
            <h2 className="text-xl font-bold text-text-primary mb-3">{t('wiki.relatedEntries')}</h2>
            <div className="grid grid-cols-1 md:grid-cols-2 gap-3">
              {entry.children.map((child) => (
                <a
                  key={child.id}
                  href={`/campaigns/${campaignId}?entry=${child.id}`}
                  className="bg-surface-elevated border border-border-theme rounded-lg p-3 hover:bg-white/5 transition-all"
                >
                  <h3 className="text-text-primary font-semibold">{child.title}</h3>
                  {child.excerpt && (
                    <p className="text-sm text-text-muted mt-1 line-clamp-2">{child.excerpt}</p>
                  )}
                </a>
              ))}
            </div>
          </div>
        )}

        {/* Actions & timestamps */}
        <div className="mt-8 pt-6 border-t border-border-theme flex flex-wrap items-center gap-3">
          {editing ? (
            <>
              <button
                onClick={handleSave}
                disabled={saving}
                className="btn-primary px-5 py-2 rounded-lg flex items-center gap-2 text-sm"
              >
                <Save className="w-4 h-4" />
                {saving ? t('common.saving') : t('common.save')}
              </button>
              <button
                onClick={() => {
                  setEditing(false)
                  setTitle(entry.title)
                  setContent(entry.content)
                }}
                className="px-5 py-2 rounded-lg border border-border-theme text-text-secondary hover:text-text-primary hover:bg-white/5 transition-colors flex items-center gap-2 text-sm"
              >
                <X className="w-4 h-4" />
                {t('common.cancel')}
              </button>
            </>
          ) : (
            <>
              <button
                onClick={() => setEditing(true)}
                className="bg-surface-elevated border border-border-theme px-5 py-2 rounded-lg text-text-secondary hover:text-text-primary transition-all flex items-center gap-2 text-sm"
              >
                <Pencil className="w-4 h-4" />
                {t('common.edit')}
              </button>
              <button
                onClick={handleDelete}
                disabled={deleting}
                className="px-5 py-2 rounded-lg bg-error/10 hover:bg-error/20 text-red-400 transition-colors flex items-center gap-2 text-sm"
              >
                <Trash2 className="w-4 h-4" />
                {deleting ? t('common.deleting') : t('common.delete')}
              </button>
            </>
          )}

          <span className="text-xs text-text-muted ml-auto">
            Created: {new Date(entry.createdAt).toLocaleDateString()}
            {' \u2022 '}
            Updated: {new Date(entry.updatedAt).toLocaleDateString()}
          </span>
        </div>
      </div>
    </div>
  )
}
