'use client'

import { useState, useCallback } from 'react'
import { WikiEntryType } from '@prisma/client'
import {
  User, MapPin, Swords, Gem, Drama, Castle,
  BookOpen, Target, FileText, ChevronRight, ChevronDown,
  Plus, RefreshCw, ArrowLeft,
} from 'lucide-react'
import WikiEntryEditor from './WikiEntryEditor'
import CreateEntryDialog from './CreateEntryDialog'
import UpdateWikiDialog from './UpdateWikiDialog'
import CharacterPdfUploadDialog from './CharacterPdfUploadDialog'
import { useI18n } from '@/lib/i18n-context'
import { Button } from '@/components/ui/button'
import type { CharacterSheetData } from '@/types/character-sheet'

const typeIcons: Record<WikiEntryType, React.ReactNode> = {
  SESSION_RECAP: <FileText className="w-3.5 h-3.5" />,
  CHARACTER: <User className="w-3.5 h-3.5" />,
  LOCATION: <MapPin className="w-3.5 h-3.5" />,
  EVENT: <Swords className="w-3.5 h-3.5" />,
  ITEM: <Gem className="w-3.5 h-3.5" />,
  NPC: <Drama className="w-3.5 h-3.5" />,
  FACTION: <Castle className="w-3.5 h-3.5" />,
  LORE: <BookOpen className="w-3.5 h-3.5" />,
  QUEST: <Target className="w-3.5 h-3.5" />,
  OTHER: <FileText className="w-3.5 h-3.5" />,
}

const wikiTypeOrder: WikiEntryType[] = [
  'CHARACTER', 'NPC', 'LOCATION', 'FACTION', 'QUEST',
  'EVENT', 'ITEM', 'LORE', 'OTHER',
]

interface WikiTreeEntry {
  id: string
  title: string
  slug: string
  type: WikiEntryType
  parentId: string | null
  createdAt: Date
}

interface ActiveEntry {
  id: string
  title: string
  type: WikiEntryType
  content: string
  tags: string[]
  isAutoGenerated: boolean
  audioFile: { id: string; filename: string } | null
  children: { id: string; title: string; excerpt: string | null }[]
  createdAt: Date
  updatedAt: Date
  characterSheet?: {
    id: string
    data: CharacterSheetData
    pdfBlobUrl: string | null
  } | null
}

interface WikiDataViewProps {
  campaignId: string
  userId: string
  entries: WikiTreeEntry[]
  activeEntry: ActiveEntry | null
  isLocked?: boolean
  onUnsavedChange: (isDirty: boolean) => void
  onNavigate: (href: string) => void
}

export default function WikiDataView({
  campaignId,
  userId,
  entries,
  activeEntry,
  isLocked,
  onUnsavedChange,
  onNavigate,
}: WikiDataViewProps) {
  const { t } = useI18n()
  const [createOpen, setCreateOpen] = useState(false)
  const [updateWikiOpen, setUpdateWikiOpen] = useState(false)
  const [pdfImportOpen, setPdfImportOpen] = useState(false)
  const [collapsed, setCollapsed] = useState<Record<string, boolean>>({})
  const [mobileShowDetail, setMobileShowDetail] = useState(!!activeEntry)

  const wikiEntries = entries.filter((e) => e.type !== 'SESSION_RECAP')

  const grouped = new Map<WikiEntryType, WikiTreeEntry[]>()
  for (const entry of wikiEntries) {
    const list = grouped.get(entry.type) || []
    list.push(entry)
    grouped.set(entry.type, list)
  }

  const toggleGroup = (key: string) => {
    setCollapsed((prev) => ({ ...prev, [key]: !prev[key] }))
  }

  const handleSelectEntry = useCallback((id: string) => {
    onNavigate(`/campaigns/${campaignId}?tab=wiki&entry=${id}`)
    setMobileShowDetail(true)
  }, [campaignId, onNavigate])

  const handleMobileBack = useCallback(() => {
    setMobileShowDetail(false)
  }, [])

  return (
    <div className="flex flex-1 overflow-hidden">
      {/* List panel */}
      <div className={`w-72 md:w-64 lg:w-72 flex-shrink-0 border-r bg-card flex flex-col overflow-hidden ${mobileShowDetail ? 'hidden md:flex' : 'flex w-full md:w-64 lg:w-72'}`}>
        {/* Actions */}
        {!isLocked && (
          <div className="flex items-center gap-2 p-3 border-b">
            <Button size="sm" onClick={() => setCreateOpen(true)} className="flex-1">
              <Plus className="w-3.5 h-3.5 mr-1.5" />
              {t('sidebar.newWikiPage')}
            </Button>
            <Button size="sm" variant="outline" onClick={() => setUpdateWikiOpen(true)} className="flex-1">
              <RefreshCw className="w-3.5 h-3.5 mr-1.5" />
              {t('sidebar.update')}
            </Button>
          </div>
        )}

        {/* Entries list */}
        <nav className="flex-1 overflow-y-auto p-2">
          {wikiEntries.length === 0 ? (
            <div className="text-center py-8 px-4">
              <BookOpen className="w-8 h-8 text-muted-foreground mx-auto mb-3 opacity-50" />
              <p className="text-sm font-medium mb-1">{t('empty.wiki')}</p>
              <p className="text-xs text-muted-foreground">{t('empty.wikiHint')}</p>
            </div>
          ) : (
            wikiTypeOrder
              .filter((type) => grouped.has(type))
              .map((type) => {
                const items = grouped.get(type)!
                const isCollapsed = collapsed[type]

                return (
                  <div key={type} className="mb-1">
                    <button
                      onClick={() => toggleGroup(type)}
                      className="w-full flex items-center gap-1.5 px-2 py-1.5 text-xs font-semibold text-muted-foreground hover:text-foreground uppercase tracking-wider transition-colors"
                    >
                      {isCollapsed ? <ChevronRight className="w-3 h-3" /> : <ChevronDown className="w-3 h-3" />}
                      {typeIcons[type]}
                      <span>{t(`wiki.type.${type}`)}</span>
                      <span className="text-muted-foreground ml-auto text-[10px]">{items.length}</span>
                    </button>

                    {!isCollapsed && (
                      <div className="ml-5">
                        {items.map((entry) => (
                          <button
                            key={entry.id}
                            onClick={() => handleSelectEntry(entry.id)}
                            className={`w-full text-left px-3 py-1.5 text-sm rounded-lg truncate transition-all ${
                              entry.id === activeEntry?.id
                                ? 'bg-primary/10 text-primary font-medium'
                                : 'text-muted-foreground hover:text-foreground hover:bg-accent'
                            }`}
                          >
                            {entry.title}
                          </button>
                        ))}
                      </div>
                    )}
                  </div>
                )
              })
          )}
        </nav>
      </div>

      {/* Detail panel */}
      <div className={`flex-1 flex flex-col overflow-hidden ${!mobileShowDetail ? 'hidden md:flex' : 'flex'}`}>
        {/* Mobile back button */}
        {mobileShowDetail && (
          <div className="md:hidden border-b px-3 py-2">
            <Button variant="ghost" size="sm" onClick={handleMobileBack}>
              <ArrowLeft className="w-4 h-4 mr-1.5" />
              {t('tabs.campaignData')}
            </Button>
          </div>
        )}

        {activeEntry ? (
          <WikiEntryEditor
            campaignId={campaignId}
            userId={userId}
            entry={activeEntry}
            onImportPdf={() => setPdfImportOpen(true)}
            onUnsavedChange={onUnsavedChange}
            isReadOnly={isLocked}
          />
        ) : (
          <div className="flex-1 flex items-center justify-center px-4">
            <div className="text-center">
              <BookOpen className="w-12 h-12 text-muted-foreground/30 mx-auto mb-3" />
              <p className="text-muted-foreground text-sm">
                {wikiEntries.length === 0 ? t('empty.wiki') : t('empty.selectEntry')}
              </p>
            </div>
          </div>
        )}
      </div>

      {/* Dialogs */}
      <CreateEntryDialog
        campaignId={campaignId}
        userId={userId}
        isOpen={createOpen}
        onClose={() => setCreateOpen(false)}
      />
      <UpdateWikiDialog
        campaignId={campaignId}
        isOpen={updateWikiOpen}
        onClose={() => setUpdateWikiOpen(false)}
      />
      <CharacterPdfUploadDialog
        campaignId={campaignId}
        userId={userId}
        wikiEntryId={activeEntry?.id || ''}
        wikiEntryTitle={activeEntry?.title || ''}
        isOpen={pdfImportOpen}
        onClose={() => setPdfImportOpen(false)}
      />
    </div>
  )
}
