'use client'

import { useState, useRef, useCallback, useEffect } from 'react'
import { useRouter } from 'next/navigation'
import { WikiEntryType } from '@prisma/client'
import { Menu, Upload, Plus, AlertTriangle } from 'lucide-react'
import Link from 'next/link'
import WikiSidebar from './WikiSidebar'
import WikiEntryEditor from './WikiEntryEditor'
import SettingsSheet from './SettingsSheet'
import AudioUploadSheet from './AudioUploadSheet'
import WikiEntryForm from './WikiEntryForm'
import CreateSessionSheet from './CreateSessionSheet'
import ChatPopup from '@/components/chat/ChatPopup'
import ChatPanel from '@/components/chat/ChatPanel'
import UpdateWikiSheet from './UpdateWikiSheet'
import CharacterPdfUploadSheet from './CharacterPdfUploadSheet'
import VoiceProfilesSheet from './VoiceProfilesSheet'
import { useI18n } from '@/lib/i18n-context'
import { Button } from '@/components/ui/button'
import { Sheet, SheetContent, SheetHeader, SheetTitle } from '@/components/ui/sheet'
import {
  AlertDialog,
  AlertDialogAction,
  AlertDialogCancel,
  AlertDialogContent,
  AlertDialogDescription,
  AlertDialogFooter,
  AlertDialogHeader,
  AlertDialogTitle,
} from '@/components/ui/alert-dialog'
import type { CharacterSheetData } from '@/types/character-sheet'

interface WikiTreeEntry {
  id: string
  title: string
  slug: string
  type: WikiEntryType
  parentId: string | null
  createdAt: Date
}

interface ActiveEntry {
  id: string
  title: string
  type: WikiEntryType
  content: string
  tags: string[]
  isAutoGenerated: boolean
  audioFile: { id: string; filename: string } | null
  children: { id: string; title: string; excerpt: string | null }[]
  createdAt: Date
  updatedAt: Date
  characterSheet?: {
    id: string
    data: CharacterSheetData
    pdfBlobUrl: string | null
  } | null
}

interface WikiPageLayoutProps {
  campaignId: string
  userId: string
  campaign: {
    name: string
    description: string | null
    language: string
  }
  wikiTree: WikiTreeEntry[]
  activeEntry: ActiveEntry | null
  dateFormat: string
  isLocked?: boolean
}

export default function WikiPageLayout({
  campaignId,
  userId,
  campaign,
  wikiTree,
  activeEntry,
  dateFormat,
  isLocked,
}: WikiPageLayoutProps) {
  const router = useRouter()
  const [settingsOpen, setSettingsOpen] = useState(false)
  const [uploadOpen, setUploadOpen] = useState(false)
  const [createOpen, setCreateOpen] = useState(false)
  const [updateWikiOpen, setUpdateWikiOpen] = useState(false)
  const [createSessionOpen, setCreateSessionOpen] = useState(false)
  const [sidebarOpen, setSidebarOpen] = useState(false)
  const [pdfImportOpen, setPdfImportOpen] = useState(false)
  const [voiceProfilesOpen, setVoiceProfilesOpen] = useState(false)
  const [pendingNav, setPendingNav] = useState<string | null>(null)
  const [sidebarWidth, setSidebarWidth] = useState(256)
  const [chatFullScreen, setChatFullScreen] = useState(false)
  const isDirtyRef = useRef(false)
  const { t } = useI18n()

  const handleUnsavedChange = useCallback((isDirty: boolean) => {
    isDirtyRef.current = isDirty
  }, [])

  const handleNavigate = useCallback((href: string) => {
    if (isDirtyRef.current) {
      setPendingNav(href)
    } else {
      setSidebarOpen(false)
      router.push(href)
    }
  }, [router])

  // Warn on browser close/refresh while dirty
  useEffect(() => {
    const handleBeforeUnload = (e: BeforeUnloadEvent) => {
      if (isDirtyRef.current) {
        e.preventDefault()
      }
    }
    window.addEventListener('beforeunload', handleBeforeUnload)
    return () => window.removeEventListener('beforeunload', handleBeforeUnload)
  }, [])

  return (
    <div className="flex flex-col h-[calc(100vh-4rem)]">
      {/* Locked plan banner */}
      {isLocked && (
        <div className="flex-shrink-0 flex items-center gap-3 px-4 py-2.5 bg-orange-500/10 border-b border-orange-500/30">
          <AlertTriangle className="w-4 h-4 text-orange-500 flex-shrink-0" />
          <p className="flex-1 text-xs sm:text-sm text-orange-700 dark:text-orange-200/90">
            {t('limits.campaignReadOnly')}
          </p>
          <Link
            href="/campaigns"
            className="flex-shrink-0 text-xs px-3 py-1 rounded-lg bg-orange-500/20 text-orange-600 dark:text-orange-300 border border-orange-500/30 hover:bg-orange-500/30 transition-colors whitespace-nowrap"
          >
            {t('sidebar.allCampaigns')}
          </Link>
        </div>
      )}

      <div className="flex flex-1 overflow-hidden">
      {/* Mobile sidebar toggle */}
      <Button
        variant="outline"
        size="icon"
        onClick={() => setSidebarOpen(true)}
        className="fixed top-[4.5rem] left-3 z-30 md:hidden"
      >
        <Menu className="w-5 h-5" />
      </Button>

      <WikiSidebar
        campaignId={campaignId}
        campaignName={campaign.name}
        entries={wikiTree}
        activeEntryId={activeEntry?.id}
        dateFormat={dateFormat}
        onSettingsClick={() => setSettingsOpen(true)}
        onUploadClick={() => setUploadOpen(true)}
        onCreateClick={() => setCreateOpen(true)}
        onUpdateWikiClick={() => setUpdateWikiOpen(true)}
        onCreateSessionClick={() => setCreateSessionOpen(true)}
        onNavigate={handleNavigate}
        isOpen={sidebarOpen}
        onClose={() => setSidebarOpen(false)}
        desktopWidth={sidebarWidth}
        onWidthChange={setSidebarWidth}
        desktopHidden={chatFullScreen}
        isLocked={isLocked}
      />

      {/* Main content */}
      {!chatFullScreen && (activeEntry ? (
        <WikiEntryEditor
          campaignId={campaignId}
          userId={userId}
          entry={activeEntry}
          onImportPdf={() => setPdfImportOpen(true)}
          onUnsavedChange={handleUnsavedChange}
          isReadOnly={isLocked}
        />
      ) : (
        <div className="flex-1 flex items-center justify-center px-4">
          <div className="text-center">
            <div className="w-16 h-16 mx-auto mb-4 rounded-2xl bg-primary/10 flex items-center justify-center">
              <svg className="w-8 h-8 text-primary" fill="none" viewBox="0 0 24 24" stroke="currentColor">
                <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={1.5} d="M12 6.253v13m0-13C10.832 5.477 9.246 5 7.5 5S4.168 5.477 3 6.253v13C4.168 18.477 5.754 18 7.5 18s3.332.477 4.5 1.253m0-13C13.168 5.477 14.754 5 16.5 5c1.747 0 3.332.477 4.5 1.253v13C19.832 18.477 18.247 18 16.5 18c-1.746 0-3.332.477-4.5 1.253" />
              </svg>
            </div>
            <p className="text-lg mb-2">
              {wikiTree.length === 0
                ? t('wiki.noEntriesYet')
                : t('wiki.selectEntry')}
            </p>
            {!isLocked && (
              <>
                <p className="text-muted-foreground text-sm mb-6">
                  {t('wiki.uploadHint')}
                </p>
                <div className="flex justify-center gap-3">
                  <Button variant="outline" onClick={() => setUploadOpen(true)}>
                    <Upload className="w-4 h-4 mr-2" />
                    {t('audio.uploadAudio')}
                  </Button>
                  <Button onClick={() => setCreateOpen(true)}>
                    <Plus className="w-4 h-4 mr-2" />
                    {t('sidebar.newPage')}
                  </Button>
                </div>
              </>
            )}
          </div>
        </div>
      ))}

      {/* Chat: desktop side panel + mobile popup */}
      {!isLocked && (
        <>
          <ChatPanel
            campaignId={campaignId}
            isFullScreen={chatFullScreen}
            onFullScreenChange={setChatFullScreen}
          />
          <div className="md:hidden">
            <ChatPopup campaignId={campaignId} />
          </div>
        </>
      )}
      </div>{/* end inner flex */}

      {/* Sheets (slide-over panels) */}
      <SettingsSheet
        campaignId={campaignId}
        userId={userId}
        campaign={campaign}
        isOpen={settingsOpen}
        onClose={() => setSettingsOpen(false)}
        onVoiceProfilesClick={() => setVoiceProfilesOpen(true)}
      />

      <VoiceProfilesSheet
        campaignId={campaignId}
        userId={userId}
        isOpen={voiceProfilesOpen}
        onClose={() => setVoiceProfilesOpen(false)}
      />

      <AudioUploadSheet
        campaignId={campaignId}
        isOpen={uploadOpen}
        onClose={() => setUploadOpen(false)}
      />

      <UpdateWikiSheet
        campaignId={campaignId}
        isOpen={updateWikiOpen}
        onClose={() => setUpdateWikiOpen(false)}
      />

      <CreateSessionSheet
        campaignId={campaignId}
        userId={userId}
        isOpen={createSessionOpen}
        onClose={() => setCreateSessionOpen(false)}
      />

      <CharacterPdfUploadSheet
        campaignId={campaignId}
        userId={userId}
        wikiEntryId={activeEntry?.id || ''}
        wikiEntryTitle={activeEntry?.title || ''}
        isOpen={pdfImportOpen}
        onClose={() => setPdfImportOpen(false)}
      />

      {/* Unsaved changes confirmation */}
      <AlertDialog open={!!pendingNav} onOpenChange={(open) => !open && setPendingNav(null)}>
        <AlertDialogContent>
          <AlertDialogHeader>
            <AlertDialogTitle>{t('unsaved.title')}</AlertDialogTitle>
            <AlertDialogDescription>{t('unsaved.message')}</AlertDialogDescription>
          </AlertDialogHeader>
          <AlertDialogFooter>
            <AlertDialogCancel>{t('common.cancel')}</AlertDialogCancel>
            <AlertDialogAction
              className="bg-destructive text-destructive-foreground hover:bg-destructive/90"
              onClick={() => {
                const href = pendingNav!
                isDirtyRef.current = false
                setPendingNav(null)
                setSidebarOpen(false)
                router.push(href)
              }}
            >
              {t('unsaved.leave')}
            </AlertDialogAction>
          </AlertDialogFooter>
        </AlertDialogContent>
      </AlertDialog>

      {/* Create entry sheet */}
      <Sheet open={createOpen} onOpenChange={(open) => !open && setCreateOpen(false)}>
        <SheetContent side="right" className="sm:max-w-lg">
          <SheetHeader>
            <SheetTitle>{t('wiki.createEntry')}</SheetTitle>
          </SheetHeader>
          <div className="mt-6">
            <WikiEntryForm
              campaignId={campaignId}
              userId={userId}
              onDone={() => setCreateOpen(false)}
            />
          </div>
        </SheetContent>
      </Sheet>
    </div>
  )
}
