'use client'

import { useState, useRef, useCallback, useEffect } from 'react'
import { useRouter, useSearchParams } from 'next/navigation'
import { WikiEntryType } from '@prisma/client'
import { Settings, AlertTriangle, ArrowLeft } from 'lucide-react'
import Link from 'next/link'
import SessionsView from './SessionsView'
import WikiDataView from './WikiDataView'
import ChatView from './ChatView'
import { useI18n } from '@/lib/i18n-context'
import { Button } from '@/components/ui/button'
import { Tabs, TabsList, TabsTrigger, TabsContent } from '@/components/ui/tabs'
import { Tooltip, TooltipContent, TooltipTrigger } from '@/components/ui/tooltip'
import {
  AlertDialog,
  AlertDialogAction,
  AlertDialogCancel,
  AlertDialogContent,
  AlertDialogDescription,
  AlertDialogFooter,
  AlertDialogHeader,
  AlertDialogTitle,
} from '@/components/ui/alert-dialog'
import type { CharacterSheetData } from '@/types/character-sheet'

interface WikiTreeEntry {
  id: string
  title: string
  slug: string
  type: WikiEntryType
  parentId: string | null
  createdAt: Date
}

interface ActiveEntry {
  id: string
  title: string
  type: WikiEntryType
  content: string
  tags: string[]
  isAutoGenerated: boolean
  audioFile: { id: string; filename: string } | null
  children: { id: string; title: string; excerpt: string | null }[]
  createdAt: Date
  updatedAt: Date
  characterSheet?: {
    id: string
    data: CharacterSheetData
    pdfBlobUrl: string | null
  } | null
}

interface WikiPageLayoutProps {
  campaignId: string
  userId: string
  campaign: {
    name: string
    description: string | null
    language: string
  }
  wikiTree: WikiTreeEntry[]
  activeEntry: ActiveEntry | null
  dateFormat: string
  isLocked?: boolean
}

export default function WikiPageLayout({
  campaignId,
  userId,
  campaign,
  wikiTree,
  activeEntry,
  dateFormat,
  isLocked,
}: WikiPageLayoutProps) {
  const router = useRouter()
  const searchParams = useSearchParams()
  const currentTab = searchParams.get('tab') || 'sessions'
  const [pendingTab, setPendingTab] = useState<string | null>(null)
  const [pendingNav, setPendingNav] = useState<string | null>(null)
  const isDirtyRef = useRef(false)
  const { t } = useI18n()

  const handleUnsavedChange = useCallback((isDirty: boolean) => {
    isDirtyRef.current = isDirty
  }, [])

  const handleTabChange = useCallback((newTab: string) => {
    if (isDirtyRef.current) {
      setPendingTab(newTab)
    } else {
      router.push(`/campaigns/${campaignId}?tab=${newTab}`)
    }
  }, [router, campaignId])

  const handleNavigate = useCallback((href: string) => {
    if (isDirtyRef.current) {
      setPendingNav(href)
    } else {
      router.push(href)
    }
  }, [router])

  // Warn on browser close/refresh while dirty
  useEffect(() => {
    const handleBeforeUnload = (e: BeforeUnloadEvent) => {
      if (isDirtyRef.current) {
        e.preventDefault()
      }
    }
    window.addEventListener('beforeunload', handleBeforeUnload)
    return () => window.removeEventListener('beforeunload', handleBeforeUnload)
  }, [])

  const confirmNavigation = useCallback(() => {
    isDirtyRef.current = false
    if (pendingTab) {
      const tab = pendingTab
      setPendingTab(null)
      router.push(`/campaigns/${campaignId}?tab=${tab}`)
    } else if (pendingNav) {
      const href = pendingNav
      setPendingNav(null)
      router.push(href)
    }
  }, [pendingTab, pendingNav, router, campaignId])

  const cancelNavigation = useCallback(() => {
    setPendingTab(null)
    setPendingNav(null)
  }, [])

  return (
    <div className="flex flex-col h-[calc(100vh-4rem)]">
      {/* Locked plan banner */}
      {isLocked && (
        <div className="flex-shrink-0 flex items-center gap-3 px-4 py-2.5 bg-orange-500/10 border-b border-orange-500/30">
          <AlertTriangle className="w-4 h-4 text-orange-500 flex-shrink-0" />
          <p className="flex-1 text-xs sm:text-sm text-orange-700 dark:text-orange-200/90">
            {t('limits.campaignReadOnly')}
          </p>
          <Link
            href="/campaigns"
            className="flex-shrink-0 text-xs px-3 py-1 rounded-lg bg-orange-500/20 text-orange-600 dark:text-orange-300 border border-orange-500/30 hover:bg-orange-500/30 transition-colors whitespace-nowrap"
          >
            {t('sidebar.allCampaigns')}
          </Link>
        </div>
      )}

      {/* Tab bar */}
      <div className="flex-shrink-0 border-b px-4 flex items-center gap-3">
        <div className="flex items-center gap-2 mr-2 py-2">
          <Link
            href="/campaigns"
            className="text-muted-foreground hover:text-foreground transition-colors"
          >
            <ArrowLeft className="w-4 h-4" />
          </Link>
          <h2 className="text-sm font-bold truncate max-w-[140px] sm:max-w-[200px]">
            {campaign.name}
          </h2>
        </div>

        <Tabs value={currentTab} onValueChange={handleTabChange} className="flex-1 flex-col-reverse min-w-0">
          <TabsList variant="line" className="h-10">
            <TabsTrigger value="sessions">{t('tabs.sessions')}</TabsTrigger>
            <TabsTrigger value="wiki">{t('tabs.campaignData')}</TabsTrigger>
            {!isLocked && (
              <TabsTrigger value="chat">{t('tabs.chat')}</TabsTrigger>
            )}
          </TabsList>
        </Tabs>

        <Tooltip>
          <TooltipTrigger asChild>
            <Button
              variant="ghost"
              size="icon"
              className="h-8 w-8 flex-shrink-0"
              asChild
            >
              <Link href={`/campaigns/${campaignId}/settings`}>
                <Settings className="w-4 h-4" />
              </Link>
            </Button>
          </TooltipTrigger>
          <TooltipContent>{t('sidebar.campaignSettings')}</TooltipContent>
        </Tooltip>
      </div>

      {/* Tab content */}
      <div className="flex-1 flex overflow-hidden">
        {currentTab === 'sessions' && (
          <SessionsView
            campaignId={campaignId}
            userId={userId}
            entries={wikiTree}
            activeEntry={activeEntry}
            dateFormat={dateFormat}
            isLocked={isLocked}
            onUnsavedChange={handleUnsavedChange}
            onNavigate={handleNavigate}
          />
        )}

        {currentTab === 'wiki' && (
          <WikiDataView
            campaignId={campaignId}
            userId={userId}
            entries={wikiTree}
            activeEntry={activeEntry}
            isLocked={isLocked}
            onUnsavedChange={handleUnsavedChange}
            onNavigate={handleNavigate}
          />
        )}

        {/* Chat stays mounted but hidden to preserve conversation state */}
        <div className={`flex-1 flex flex-col ${currentTab === 'chat' ? '' : 'hidden'}`}>
          <ChatView campaignId={campaignId} />
        </div>
      </div>

      {/* Unsaved changes confirmation */}
      <AlertDialog open={!!pendingTab || !!pendingNav} onOpenChange={(open) => !open && cancelNavigation()}>
        <AlertDialogContent>
          <AlertDialogHeader>
            <AlertDialogTitle>{t('unsaved.title')}</AlertDialogTitle>
            <AlertDialogDescription>{t('unsaved.message')}</AlertDialogDescription>
          </AlertDialogHeader>
          <AlertDialogFooter>
            <AlertDialogCancel>{t('common.cancel')}</AlertDialogCancel>
            <AlertDialogAction
              className="bg-destructive text-destructive-foreground hover:bg-destructive/90"
              onClick={confirmNavigation}
            >
              {t('unsaved.leave')}
            </AlertDialogAction>
          </AlertDialogFooter>
        </AlertDialogContent>
      </AlertDialog>
    </div>
  )
}
