'use client'

import { useState, useEffect, useRef } from 'react'
import { useRouter } from 'next/navigation'
import { updateWikiEntry, deleteWikiEntry } from '@/actions/wiki'
import { createCharacterSheet } from '@/actions/character-sheet'
import { WikiEntryType } from '@prisma/client'
import { Pencil, Trash2, Save, X, Sparkles, Music, LayoutGrid, FileText, Plus, Upload } from 'lucide-react'
import { useI18n } from '@/lib/i18n-context'
import CharacterSheetBoard from '@/components/character-sheet/CharacterSheetBoard'
import { createEmptyCharacterSheet } from '@/types/character-sheet'
import type { CharacterSheetData } from '@/types/character-sheet'

const typeColors: Record<WikiEntryType, string> = {
  SESSION_RECAP: 'bg-accent-purple/20 text-accent-purple-light',
  CHARACTER: 'bg-blue-500/20 text-blue-300',
  LOCATION: 'bg-emerald-500/20 text-emerald-300',
  EVENT: 'bg-red-500/20 text-red-300',
  ITEM: 'bg-amber-500/20 text-amber-300',
  NPC: 'bg-pink-500/20 text-pink-300',
  FACTION: 'bg-cyan-500/20 text-cyan-300',
  LORE: 'bg-indigo-500/20 text-indigo-300',
  QUEST: 'bg-orange-500/20 text-orange-300',
  OTHER: 'bg-gray-500/20 text-gray-300',
}

interface WikiEntryEditorProps {
  campaignId: string
  userId: string
  entry: {
    id: string
    title: string
    type: WikiEntryType
    content: string
    tags: string[]
    isAutoGenerated: boolean
    audioFile: { id: string; filename: string } | null
    children: { id: string; title: string; excerpt: string | null }[]
    createdAt: Date
    updatedAt: Date
    characterSheet?: {
      id: string
      data: CharacterSheetData
      pdfBlobUrl: string | null
    } | null
  }
  onImportPdf?: () => void
  onUnsavedChange?: (isDirty: boolean) => void
  isReadOnly?: boolean
}

export default function WikiEntryEditor({ campaignId, userId, entry, onImportPdf, onUnsavedChange, isReadOnly }: WikiEntryEditorProps) {
  const router = useRouter()
  const [editing, setEditing] = useState(false)
  const [title, setTitle] = useState(entry.title)
  const [content, setContent] = useState(entry.content)
  const [saving, setSaving] = useState(false)
  const [deleting, setDeleting] = useState(false)
  const [viewMode, setViewMode] = useState<'board' | 'wiki'>(entry.characterSheet ? 'board' : 'wiki')
  const [creatingSheet, setCreatingSheet] = useState(false)
  const { t } = useI18n()

  const isCharacter = entry.type === 'CHARACTER'
  const hasSheet = !!entry.characterSheet

  // Ref so we can call onUnsavedChange inside effects without it being a dep
  const onUnsavedChangeRef = useRef(onUnsavedChange)
  onUnsavedChangeRef.current = onUnsavedChange

  useEffect(() => {
    setEditing(false)
    setTitle(entry.title)
    setContent(entry.content)
    setViewMode(entry.characterSheet ? 'board' : 'wiki')
    onUnsavedChangeRef.current?.(false)
  // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [entry.id])

  const handleSave = async () => {
    setSaving(true)
    try {
      await updateWikiEntry(entry.id, userId, { title, content })
      setEditing(false)
      onUnsavedChange?.(false)
      router.refresh()
    } catch (err) {
      alert(err instanceof Error ? err.message : 'Failed to save')
    } finally {
      setSaving(false)
    }
  }

  const handleDelete = async () => {
    if (!confirm('Are you sure you want to delete this entry? This cannot be undone.')) return
    setDeleting(true)
    try {
      await deleteWikiEntry(entry.id, userId)
      router.push(`/campaigns/${campaignId}`)
      router.refresh()
    } catch (err) {
      alert(err instanceof Error ? err.message : 'Failed to delete')
      setDeleting(false)
    }
  }

  const handleCreateBlankSheet = async () => {
    setCreatingSheet(true)
    try {
      const emptyData = createEmptyCharacterSheet()
      emptyData.characterName = entry.title
      await createCharacterSheet(campaignId, userId, entry.id, emptyData)
      router.refresh()
    } catch (err) {
      alert(err instanceof Error ? err.message : 'Failed to create character sheet')
    } finally {
      setCreatingSheet(false)
    }
  }

  // Board view for characters with sheet data
  if (isCharacter && hasSheet && viewMode === 'board') {
    return (
      <div className="flex-1 overflow-y-auto">
        {/* View toggle bar */}
        <div className="sticky top-0 z-10 bg-surface/80 backdrop-blur-sm border-b border-border-theme px-4 py-2 flex items-center justify-between">
          <div className="flex items-center gap-2">
            <button
              onClick={() => setViewMode('board')}
              className="flex items-center gap-1 text-xs px-3 py-1.5 rounded-lg transition-colors bg-accent-purple/20 text-accent-purple-light"
            >
              <LayoutGrid className="w-3.5 h-3.5" />
              {t('characterSheet.boardView')}
            </button>
            <button
              onClick={() => setViewMode('wiki')}
              className="flex items-center gap-1 text-xs px-3 py-1.5 rounded-lg transition-colors text-text-muted hover:text-text-primary"
            >
              <FileText className="w-3.5 h-3.5" />
              {t('characterSheet.wikiView')}
            </button>
          </div>
        </div>
        <CharacterSheetBoard
          key={entry.characterSheet!.id}
          characterSheetId={entry.characterSheet!.id}
          userId={userId}
          campaignId={campaignId}
          initialData={entry.characterSheet!.data}
          pdfBlobUrl={entry.characterSheet!.pdfBlobUrl}
          onBack={() => setViewMode('wiki')}
          onUnsavedChange={onUnsavedChange}
        />
      </div>
    )
  }

  return (
    <div className="flex-1 overflow-y-auto p-4 sm:p-6 lg:p-8">
      {/* View toggle for characters with sheet */}
      {isCharacter && hasSheet && viewMode === 'wiki' && (
        <div className="mb-4 flex items-center gap-2">
          <button
            onClick={() => setViewMode('board')}
            className="flex items-center gap-1 text-xs px-3 py-1.5 rounded-lg text-text-muted hover:text-accent-purple-light hover:bg-accent-purple/10 transition-colors"
          >
            <LayoutGrid className="w-3.5 h-3.5" />
            {t('characterSheet.boardView')}
          </button>
          <button
            className="flex items-center gap-1 text-xs px-3 py-1.5 rounded-lg bg-accent-purple/20 text-accent-purple-light"
          >
            <FileText className="w-3.5 h-3.5" />
            {t('characterSheet.wikiView')}
          </button>
        </div>
      )}

      <div className="max-w-4xl">
        {/* Header */}
        <div className="mb-6 relative">
          <div className="flex items-start gap-3">
            <div className="flex-1 min-w-0">
              {editing ? (
                <input
                  type="text"
                  value={title}
                  onChange={(e) => setTitle(e.target.value)}
                  className="text-2xl sm:text-3xl font-bold text-text-primary bg-transparent border-b border-border-theme focus:border-accent-purple focus:outline-none w-full pb-1"
                />
              ) : (
                <h1 className="text-2xl sm:text-3xl font-bold text-text-primary text-glow">{entry.title}</h1>
              )}
            </div>

            {/* Action icons */}
            {!isReadOnly && (
              <div className="flex items-center gap-1 flex-shrink-0 pt-1">
                {editing ? (
                  <>
                    <button
                      onClick={handleSave}
                      disabled={saving}
                      className="p-2 rounded-lg text-text-muted hover:text-accent-purple-light hover:bg-accent-purple/10 transition-colors"
                      title={saving ? t('common.saving') : t('common.save')}
                    >
                      <Save className="w-4 h-4" />
                    </button>
                    <button
                      onClick={() => {
                        setEditing(false)
                        setTitle(entry.title)
                        setContent(entry.content)
                        onUnsavedChange?.(false)
                      }}
                      className="p-2 rounded-lg text-text-muted hover:text-text-primary hover:bg-white/5 transition-colors"
                      title={t('common.cancel')}
                    >
                      <X className="w-4 h-4" />
                    </button>
                  </>
                ) : (
                  <>
                    <button
                      onClick={() => { setEditing(true); onUnsavedChange?.(true) }}
                      className="p-2 rounded-lg text-text-muted hover:text-accent-purple-light hover:bg-accent-purple/10 transition-colors"
                      title={t('common.edit')}
                    >
                      <Pencil className="w-4 h-4" />
                    </button>
                    <button
                      onClick={handleDelete}
                      disabled={deleting}
                      className="p-2 rounded-lg text-text-muted hover:text-red-400 hover:bg-error/10 transition-colors"
                      title={deleting ? t('common.deleting') : t('common.delete')}
                    >
                      <Trash2 className="w-4 h-4" />
                    </button>
                  </>
                )}
              </div>
            )}
          </div>

          <div className="flex flex-wrap items-center gap-2 mt-3">
            <span className={`text-xs font-medium px-3 py-1 rounded-full ${typeColors[entry.type]}`}>
              {t(`wiki.typeSingle.${entry.type}`)}
            </span>
            {entry.tags.map((tag) => (
              <span
                key={tag}
                className="text-xs bg-white/5 text-text-muted px-3 py-1 rounded-full border border-border-theme"
              >
                {tag}
              </span>
            ))}
            {entry.isAutoGenerated && (
              <span className="text-xs bg-accent-purple/10 text-accent-purple-light px-3 py-1 rounded-full flex items-center gap-1">
                <Sparkles className="w-3 h-3" />
                {t('wiki.autoGenerated')}
              </span>
            )}
          </div>
        </div>

        {/* Character sheet prompt for CHARACTER entries without a sheet */}
        {isCharacter && !hasSheet && !editing && !isReadOnly && (
          <div className="mb-6 p-4 rounded-lg bg-surface-elevated border border-dashed border-accent-purple/30">
            <p className="text-sm text-text-secondary mb-3">{t('characterSheet.addPrompt')}</p>
            <div className="flex flex-wrap gap-2">
              <button
                onClick={handleCreateBlankSheet}
                disabled={creatingSheet}
                className="flex items-center gap-1.5 text-xs px-3 py-2 rounded-lg btn-primary"
              >
                <Plus className="w-3.5 h-3.5" />
                {creatingSheet ? t('common.creating') : t('characterSheet.createBlank')}
              </button>
              {onImportPdf && (
                <button
                  onClick={onImportPdf}
                  className="flex items-center gap-1.5 text-xs px-3 py-2 rounded-lg bg-surface border border-border-theme text-text-secondary hover:text-text-primary transition-colors"
                >
                  <Upload className="w-3.5 h-3.5" />
                  {t('characterSheet.importPdf')}
                </button>
              )}
            </div>
          </div>
        )}

        {/* Source audio */}
        {entry.audioFile && (
          <div className="mb-6 p-3 rounded-lg bg-surface-elevated border border-border-theme flex items-center gap-2">
            <Music className="w-4 h-4 text-text-muted" />
            <p className="text-sm text-text-muted">
              {t('wiki.source')}: <span className="text-text-secondary">{entry.audioFile.filename}</span>
            </p>
          </div>
        )}

        {/* Content */}
        {editing ? (
          <textarea
            value={content}
            onChange={(e) => setContent(e.target.value)}
            rows={20}
            className="w-full px-4 py-3 rounded-lg input-dark leading-relaxed resize-y text-sm sm:text-base"
          />
        ) : (
          <div className="text-text-secondary whitespace-pre-wrap leading-relaxed text-sm sm:text-base">
            {entry.content}
          </div>
        )}

        {/* Related entries */}
        {!editing && entry.children.length > 0 && (
          <div className="mt-8">
            <h2 className="text-xl font-bold text-text-primary mb-3">{t('wiki.relatedEntries')}</h2>
            <div className="grid grid-cols-1 md:grid-cols-2 gap-3">
              {entry.children.map((child) => (
                <a
                  key={child.id}
                  href={`/campaigns/${campaignId}?entry=${child.id}`}
                  className="bg-surface-elevated border border-border-theme rounded-lg p-3 hover:bg-white/5 transition-all"
                >
                  <h3 className="text-text-primary font-semibold">{child.title}</h3>
                  {child.excerpt && (
                    <p className="text-sm text-text-muted mt-1 line-clamp-2">{child.excerpt}</p>
                  )}
                </a>
              ))}
            </div>
          </div>
        )}

        {/* Timestamps */}
        <div className="mt-8 pt-6 border-t border-border-theme">
          <span className="text-xs text-text-muted">
            Created: {new Date(entry.createdAt).toLocaleDateString()}
            {' \u2022 '}
            Updated: {new Date(entry.updatedAt).toLocaleDateString()}
          </span>
        </div>
      </div>
    </div>
  )
}
