'use client'

import { useState } from 'react'
import { WikiEntryType } from '@prisma/client'
import { Menu, Upload, Plus } from 'lucide-react'
import WikiSidebar from './WikiSidebar'
import WikiEntryEditor from './WikiEntryEditor'
import SettingsModal from './SettingsModal'
import AudioUploadModal from './AudioUploadModal'
import WikiEntryForm from './WikiEntryForm'
import ChatPopup from '@/components/chat/ChatPopup'
import ChatPanel from '@/components/chat/ChatPanel'
import UpdateWikiModal from './UpdateWikiModal'
import CharacterPdfUploadModal from './CharacterPdfUploadModal'
import { useI18n } from '@/lib/i18n-context'
import type { CharacterSheetData } from '@/types/character-sheet'
import PlayersModal from './PlayersModal'

interface WikiTreeEntry {
  id: string
  title: string
  slug: string
  type: WikiEntryType
  parentId: string | null
  createdAt: Date
}

interface ActiveEntry {
  id: string
  title: string
  type: WikiEntryType
  content: string
  tags: string[]
  isAutoGenerated: boolean
  audioFile: { id: string; filename: string } | null
  children: { id: string; title: string; excerpt: string | null }[]
  createdAt: Date
  updatedAt: Date
  characterSheet?: {
    id: string
    data: CharacterSheetData
    pdfBlobUrl: string | null
  } | null
}

interface CharacterSheetSummary {
  id: string
  assignedPlayerId: string | null
  wikiEntry: { id: string; title: string }
}

interface WikiPageLayoutProps {
  campaignId: string
  userId: string
  campaign: {
    name: string
    description: string | null
    language: string
  }
  wikiTree: WikiTreeEntry[]
  activeEntry: ActiveEntry | null
  characterSheets: CharacterSheetSummary[]
}

export default function WikiPageLayout({
  campaignId,
  userId,
  campaign,
  wikiTree,
  activeEntry,
  characterSheets,
}: WikiPageLayoutProps) {
  const [settingsOpen, setSettingsOpen] = useState(false)
  const [uploadOpen, setUploadOpen] = useState(false)
  const [createOpen, setCreateOpen] = useState(false)
  const [updateWikiOpen, setUpdateWikiOpen] = useState(false)
  const [sidebarOpen, setSidebarOpen] = useState(false)
  const [pdfImportOpen, setPdfImportOpen] = useState(false)
  const [playersOpen, setPlayersOpen] = useState(false)
  const { t } = useI18n()

  return (
    <div className="flex h-[calc(100vh-4rem)] overflow-hidden">
      {/* Mobile sidebar toggle */}
      <button
        onClick={() => setSidebarOpen(true)}
        className="fixed top-[4.5rem] left-3 z-30 md:hidden p-2 rounded-lg bg-surface-elevated border border-border-theme text-text-secondary hover:text-text-primary transition-colors"
      >
        <Menu className="w-5 h-5" />
      </button>

      <WikiSidebar
        campaignId={campaignId}
        campaignName={campaign.name}
        entries={wikiTree}
        activeEntryId={activeEntry?.id}
        onSettingsClick={() => setSettingsOpen(true)}
        onPlayersClick={() => setPlayersOpen(true)}
        onUploadClick={() => setUploadOpen(true)}
        onCreateClick={() => setCreateOpen(true)}
        onUpdateWikiClick={() => setUpdateWikiOpen(true)}
        isOpen={sidebarOpen}
        onClose={() => setSidebarOpen(false)}
      />

      {/* Main content */}
      {activeEntry ? (
        <WikiEntryEditor
          campaignId={campaignId}
          userId={userId}
          entry={activeEntry}
          onImportPdf={() => setPdfImportOpen(true)}
        />
      ) : (
        <div className="flex-1 flex items-center justify-center px-4">
          <div className="text-center">
            <div className="w-16 h-16 mx-auto mb-4 rounded-2xl bg-accent-purple/10 flex items-center justify-center">
              <svg className="w-8 h-8 text-accent-purple-light" fill="none" viewBox="0 0 24 24" stroke="currentColor">
                <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={1.5} d="M12 6.253v13m0-13C10.832 5.477 9.246 5 7.5 5S4.168 5.477 3 6.253v13C4.168 18.477 5.754 18 7.5 18s3.332.477 4.5 1.253m0-13C13.168 5.477 14.754 5 16.5 5c1.747 0 3.332.477 4.5 1.253v13C19.832 18.477 18.247 18 16.5 18c-1.746 0-3.332.477-4.5 1.253" />
              </svg>
            </div>
            <p className="text-text-secondary text-lg mb-2">
              {wikiTree.length === 0
                ? t('wiki.noEntriesYet')
                : t('wiki.selectEntry')}
            </p>
            <p className="text-text-muted text-sm mb-6">
              {t('wiki.uploadHint')}
            </p>
            <div className="flex justify-center gap-3">
              <button
                onClick={() => setUploadOpen(true)}
                className="text-sm px-4 py-2.5 rounded-lg bg-surface-elevated border border-border-theme text-text-secondary hover:text-text-primary transition-all flex items-center gap-2"
              >
                <Upload className="w-4 h-4" />
                {t('audio.uploadAudio')}
              </button>
              <button
                onClick={() => setCreateOpen(true)}
                className="text-sm px-4 py-2.5 rounded-lg btn-primary flex items-center gap-2"
              >
                <Plus className="w-4 h-4" />
                {t('sidebar.newPage')}
              </button>
            </div>
          </div>
        </div>
      )}

      {/* Chat: desktop side panel + mobile popup */}
      <ChatPanel campaignId={campaignId} />
      <div className="md:hidden">
        <ChatPopup campaignId={campaignId} />
      </div>

      {/* Modals */}
      <SettingsModal
        campaignId={campaignId}
        userId={userId}
        campaign={campaign}
        isOpen={settingsOpen}
        onClose={() => setSettingsOpen(false)}
      />

      <AudioUploadModal
        campaignId={campaignId}
        isOpen={uploadOpen}
        onClose={() => setUploadOpen(false)}
      />

      <UpdateWikiModal
        campaignId={campaignId}
        isOpen={updateWikiOpen}
        onClose={() => setUpdateWikiOpen(false)}
      />

      <PlayersModal
        campaignId={campaignId}
        userId={userId}
        characterSheets={characterSheets}
        isOpen={playersOpen}
        onClose={() => setPlayersOpen(false)}
      />

      <CharacterPdfUploadModal
        campaignId={campaignId}
        userId={userId}
        wikiEntryId={activeEntry?.id || ''}
        wikiEntryTitle={activeEntry?.title || ''}
        isOpen={pdfImportOpen}
        onClose={() => setPdfImportOpen(false)}
      />

      {/* Create entry modal */}
      {createOpen && (
        <div className="fixed inset-0 z-50 flex items-center justify-center">
          <div className="absolute inset-0 bg-black/60 backdrop-blur-sm" onClick={() => setCreateOpen(false)} />
          <div className="relative rounded-xl w-full max-w-lg mx-3 bg-surface border border-border-theme">
            <div className="flex items-center justify-between p-6 border-b border-border-theme">
              <h2 className="text-xl font-bold text-text-primary">{t('wiki.createEntry')}</h2>
              <button
                onClick={() => setCreateOpen(false)}
                className="text-text-muted hover:text-text-primary text-xl transition-colors"
              >
                &times;
              </button>
            </div>
            <div className="p-6">
              <WikiEntryForm
                campaignId={campaignId}
                userId={userId}
                onDone={() => setCreateOpen(false)}
              />
            </div>
          </div>
        </div>
      )}
    </div>
  )
}
