'use client'

import { useState, useEffect } from 'react'
import { useRouter } from 'next/navigation'
import { updateWikiEntry, deleteWikiEntry } from '@/actions/wiki'
import { WikiEntryType } from '@prisma/client'

const typeLabels: Record<WikiEntryType, string> = {
  SESSION_RECAP: 'Session Recap',
  CHARACTER: 'Character',
  LOCATION: 'Location',
  EVENT: 'Event',
  ITEM: 'Item',
  NPC: 'NPC',
  FACTION: 'Faction',
  LORE: 'Lore',
  QUEST: 'Quest',
  OTHER: 'Other',
}

interface WikiEntryEditorProps {
  campaignId: string
  userId: string
  entry: {
    id: string
    title: string
    type: WikiEntryType
    content: string
    tags: string[]
    isAutoGenerated: boolean
    audioFile: { id: string; filename: string } | null
    children: { id: string; title: string; excerpt: string | null }[]
    createdAt: Date
    updatedAt: Date
  }
}

export default function WikiEntryEditor({ campaignId, userId, entry }: WikiEntryEditorProps) {
  const router = useRouter()
  const [editing, setEditing] = useState(false)
  const [title, setTitle] = useState(entry.title)
  const [content, setContent] = useState(entry.content)
  const [saving, setSaving] = useState(false)
  const [deleting, setDeleting] = useState(false)

  // Reset state when entry changes
  useEffect(() => {
    setEditing(false)
    setTitle(entry.title)
    setContent(entry.content)
  }, [entry.id, entry.title, entry.content])

  const handleSave = async () => {
    setSaving(true)
    try {
      await updateWikiEntry(entry.id, userId, { title, content })
      setEditing(false)
      router.refresh()
    } catch (err) {
      alert(err instanceof Error ? err.message : 'Failed to save')
    } finally {
      setSaving(false)
    }
  }

  const handleDelete = async () => {
    if (!confirm('Are you sure you want to delete this entry? This cannot be undone.')) return
    setDeleting(true)
    try {
      await deleteWikiEntry(entry.id, userId)
      router.push(`/campaigns/${campaignId}`)
      router.refresh()
    } catch (err) {
      alert(err instanceof Error ? err.message : 'Failed to delete')
      setDeleting(false)
    }
  }

  return (
    <div className="flex-1 overflow-y-auto p-6 lg:p-8">
      <div className="max-w-4xl">
        {/* Header */}
        <div className="mb-6">
          {editing ? (
            <input
              type="text"
              value={title}
              onChange={(e) => setTitle(e.target.value)}
              className="text-3xl font-bold text-white bg-transparent border-b border-gray-600 focus:border-blue-500 focus:outline-none w-full pb-1"
            />
          ) : (
            <h1 className="text-3xl font-bold text-white">{entry.title}</h1>
          )}

          <div className="flex flex-wrap items-center gap-2 mt-3">
            <span className="text-sm bg-gray-700 text-gray-300 px-3 py-1 rounded">
              {typeLabels[entry.type]}
            </span>
            {entry.tags.map((tag) => (
              <span
                key={tag}
                className="text-sm bg-gray-800 text-gray-400 px-3 py-1 rounded"
              >
                {tag}
              </span>
            ))}
            {entry.isAutoGenerated && (
              <span className="text-sm bg-blue-500/20 text-blue-300 px-3 py-1 rounded">
                Auto-generated
              </span>
            )}
          </div>
        </div>

        {/* Source audio */}
        {entry.audioFile && (
          <div className="mb-6 p-3 bg-gray-900 rounded-lg">
            <p className="text-sm text-gray-500">
              Source: <span className="text-gray-300">{entry.audioFile.filename}</span>
            </p>
          </div>
        )}

        {/* Content */}
        {editing ? (
          <textarea
            value={content}
            onChange={(e) => setContent(e.target.value)}
            rows={20}
            className="w-full px-4 py-3 rounded-lg bg-gray-900 border border-gray-700 text-gray-300 leading-relaxed focus:outline-none focus:ring-2 focus:ring-blue-500 resize-y"
          />
        ) : (
          <div className="text-gray-300 whitespace-pre-wrap leading-relaxed">
            {entry.content}
          </div>
        )}

        {/* Related entries */}
        {!editing && entry.children.length > 0 && (
          <div className="mt-8">
            <h2 className="text-xl font-bold text-white mb-3">Related Entries</h2>
            <div className="grid grid-cols-1 md:grid-cols-2 gap-3">
              {entry.children.map((child) => (
                <a
                  key={child.id}
                  href={`/campaigns/${campaignId}?entry=${child.id}`}
                  className="bg-gray-800 rounded-lg p-3 hover:bg-gray-700 transition-colors"
                >
                  <h3 className="text-white font-semibold">{child.title}</h3>
                  {child.excerpt && (
                    <p className="text-sm text-gray-500 mt-1 line-clamp-2">{child.excerpt}</p>
                  )}
                </a>
              ))}
            </div>
          </div>
        )}

        {/* Actions & timestamps */}
        <div className="mt-8 pt-6 border-t border-gray-700 flex flex-wrap items-center gap-3">
          {editing ? (
            <>
              <button
                onClick={handleSave}
                disabled={saving}
                className="bg-blue-600 hover:bg-blue-700 disabled:bg-blue-800 text-white font-semibold px-5 py-2 rounded-lg transition-colors"
              >
                {saving ? 'Saving...' : 'Save'}
              </button>
              <button
                onClick={() => {
                  setEditing(false)
                  setTitle(entry.title)
                  setContent(entry.content)
                }}
                className="px-5 py-2 rounded-lg border border-gray-700 text-gray-300 hover:bg-gray-800 transition-colors"
              >
                Cancel
              </button>
            </>
          ) : (
            <>
              <button
                onClick={() => setEditing(true)}
                className="bg-gray-700 hover:bg-gray-600 text-white font-semibold px-5 py-2 rounded-lg transition-colors"
              >
                Edit
              </button>
              <button
                onClick={handleDelete}
                disabled={deleting}
                className="bg-red-600/20 hover:bg-red-600/30 text-red-300 font-semibold px-5 py-2 rounded-lg transition-colors"
              >
                {deleting ? 'Deleting...' : 'Delete'}
              </button>
            </>
          )}

          <span className="text-sm text-gray-500 ml-auto">
            Created: {new Date(entry.createdAt).toLocaleDateString()}
            {' \u2022 '}
            Updated: {new Date(entry.updatedAt).toLocaleDateString()}
          </span>
        </div>
      </div>
    </div>
  )
}
