export type Locale = 'en' | 'it'

const en = {
  // Nav
  'nav.campaigns': 'Campaigns',
  'nav.profile': 'Profile',
  'nav.signOut': 'Sign Out',

  // Sidebar
  'sidebar.allCampaigns': 'All Campaigns',
  'sidebar.upload': 'Upload',
  'sidebar.newPage': 'New Page',
  'sidebar.update': 'Update',
  'sidebar.sessionRecaps': 'Session Recaps',
  'sidebar.campaignWiki': 'Campaign Wiki',
  'sidebar.noEntries': 'No entries yet',
  'sidebar.campaignSettings': 'Campaign settings',

  // Wiki type labels (plural, for sidebar groups)
  'wiki.type.SESSION_RECAP': 'Session Recaps',
  'wiki.type.CHARACTER': 'Characters',
  'wiki.type.LOCATION': 'Locations',
  'wiki.type.EVENT': 'Events',
  'wiki.type.ITEM': 'Items',
  'wiki.type.NPC': 'NPCs',
  'wiki.type.FACTION': 'Factions',
  'wiki.type.LORE': 'Lore',
  'wiki.type.QUEST': 'Quests',
  'wiki.type.OTHER': 'Other',

  // Wiki type labels (singular, for badges)
  'wiki.typeSingle.SESSION_RECAP': 'Session Recap',
  'wiki.typeSingle.CHARACTER': 'Character',
  'wiki.typeSingle.LOCATION': 'Location',
  'wiki.typeSingle.EVENT': 'Event',
  'wiki.typeSingle.ITEM': 'Item',
  'wiki.typeSingle.NPC': 'NPC',
  'wiki.typeSingle.FACTION': 'Faction',
  'wiki.typeSingle.LORE': 'Lore',
  'wiki.typeSingle.QUEST': 'Quest',
  'wiki.typeSingle.OTHER': 'Other',

  // Wiki editor
  'wiki.autoGenerated': 'Auto-generated',
  'wiki.source': 'Source',
  'wiki.relatedEntries': 'Related Entries',
  'wiki.noEntriesYet': 'No wiki entries yet',
  'wiki.selectEntry': 'Select an entry from the sidebar',
  'wiki.uploadHint': 'Upload audio to generate entries automatically, or create one manually',
  'wiki.createEntry': 'Create Wiki Entry',

  // Wiki form
  'wiki.form.title': 'Title *',
  'wiki.form.titlePlaceholder': 'e.g. Eldrin the Wise',
  'wiki.form.type': 'Type *',
  'wiki.form.content': 'Content *',
  'wiki.form.contentPlaceholder': 'Write the wiki entry content...',
  'wiki.form.tags': 'Tags (comma-separated)',
  'wiki.form.tagsPlaceholder': 'e.g. wizard, ally, magic',

  // Common actions
  'common.save': 'Save',
  'common.saving': 'Saving...',
  'common.cancel': 'Cancel',
  'common.delete': 'Delete',
  'common.deleting': 'Deleting...',
  'common.edit': 'Edit',
  'common.close': 'Close',
  'common.confirm': 'Confirm',
  'common.createEntry': 'Create Entry',

  // Chat
  'chat.title': 'DM Companion',
  'chat.placeholder': 'Ask about your campaign or generate content...',
  'chat.emptyTitle': 'Your DM assistant is ready!',
  'chat.emptySubtitle': 'Ask about your campaign, or generate NPCs, locations, encounters, and more.',
  'chat.openPanel': 'Open chat',
  'chat.closePanel': 'Close chat',
  'chat.you': 'You',
  'chat.error': 'Sorry, I encountered an error. Please try again.',

  // Campaigns
  'campaigns.title': 'Your Campaigns',
  'campaigns.create': 'Create Campaign',
  'campaigns.noCampaigns': 'No campaigns yet',
  'campaigns.createFirst': 'Create Your First Campaign',
  'campaigns.audio': 'audio',
  'campaigns.wiki': 'wiki',
  'campaigns.rename': 'Rename',

  // Campaign creation
  'campaigns.new.title': 'Create New Campaign',
  'campaigns.new.name': 'Campaign Name *',
  'campaigns.new.namePlaceholder': 'The Dragon\'s Lair',
  'campaigns.new.description': 'Description',
  'campaigns.new.descPlaceholder': 'A thrilling adventure through ancient ruins...',
  'campaigns.new.language': 'Language',
  'campaigns.new.languageHint': 'Wiki entries, summaries, and chat will use this language.',

  // Settings modal
  'settings.title': 'Campaign Settings',
  'settings.name': 'Campaign Name *',
  'settings.description': 'Description',
  'settings.language': 'Language',
  'settings.saveChanges': 'Save Changes',
  'settings.dangerZone': 'Danger Zone',
  'settings.dangerText': 'Permanently delete this campaign and all its data.',
  'settings.deleteCampaign': 'Delete Campaign',

  // Audio upload modal
  'audio.uploadTitle': 'Upload Session Recording',
  'audio.uploadSubtitle': 'Upload audio to auto-transcribe and generate wiki entries',
  'audio.dragDrop': 'Drag & drop an audio file here',
  'audio.dropHere': 'Drop the file here',
  'audio.orBrowse': 'or click to browse',
  'audio.formats': 'MP3, WAV, M4A, OGG (max 100MB)',
  'audio.uploading': 'Uploading...',
  'audio.creating': 'Creating record...',
  'audio.processing': 'Processing audio (transcribing, summarizing, generating wiki entries)...',
  'audio.done': 'Done! Wiki entries generated.',
  'audio.error': 'Something went wrong.',
  'audio.waitNote': 'This may take a few minutes for longer recordings',
  'audio.tryAgain': 'Try again',
  'audio.uploadAudio': 'Upload Audio',

  // Update wiki modal
  'updateWiki.title': 'Update Wiki',
  'updateWiki.description': 'Analyze all session recaps and create or update wiki entries for characters, locations, items, and more.',
  'updateWiki.instructions': 'Additional instructions (optional)',
  'updateWiki.instructionsPlaceholder': 'e.g. Focus on the new NPCs from the latest session',
  'updateWiki.generate': 'Generate Wiki',
  'updateWiki.analyzing': 'Analyzing sessions...',
  'updateWiki.done': 'Done! Created {created} and updated {updated} entries.',

  // Profile
  'profile.title': 'Profile',
  'profile.displayName': 'Display Name',
  'profile.displayNamePlaceholder': 'Your name',
  'profile.uiLanguage': 'UI Language',
  'profile.saved': 'Saved!',
  'profile.memberSince': 'Member since',
  'profile.noName': 'No name set',
} as const

const it: Record<string, string> = {
  // Nav
  'nav.campaigns': 'Campagne',
  'nav.profile': 'Profilo',
  'nav.signOut': 'Esci',

  // Sidebar
  'sidebar.allCampaigns': 'Tutte le Campagne',
  'sidebar.upload': 'Carica',
  'sidebar.newPage': 'Nuova Pagina',
  'sidebar.update': 'Aggiorna',
  'sidebar.sessionRecaps': 'Riepiloghi Sessione',
  'sidebar.campaignWiki': 'Wiki Campagna',
  'sidebar.noEntries': 'Nessuna voce',
  'sidebar.campaignSettings': 'Impostazioni campagna',

  // Wiki type labels (plural)
  'wiki.type.SESSION_RECAP': 'Riepiloghi Sessione',
  'wiki.type.CHARACTER': 'Personaggi',
  'wiki.type.LOCATION': 'Luoghi',
  'wiki.type.EVENT': 'Eventi',
  'wiki.type.ITEM': 'Oggetti',
  'wiki.type.NPC': 'PNG',
  'wiki.type.FACTION': 'Fazioni',
  'wiki.type.LORE': 'Ambientazione',
  'wiki.type.QUEST': 'Missioni',
  'wiki.type.OTHER': 'Altro',

  // Wiki type labels (singular)
  'wiki.typeSingle.SESSION_RECAP': 'Riepilogo Sessione',
  'wiki.typeSingle.CHARACTER': 'Personaggio',
  'wiki.typeSingle.LOCATION': 'Luogo',
  'wiki.typeSingle.EVENT': 'Evento',
  'wiki.typeSingle.ITEM': 'Oggetto',
  'wiki.typeSingle.NPC': 'PNG',
  'wiki.typeSingle.FACTION': 'Fazione',
  'wiki.typeSingle.LORE': 'Ambientazione',
  'wiki.typeSingle.QUEST': 'Missione',
  'wiki.typeSingle.OTHER': 'Altro',

  // Wiki editor
  'wiki.autoGenerated': 'Auto-generato',
  'wiki.source': 'Fonte',
  'wiki.relatedEntries': 'Voci Correlate',
  'wiki.noEntriesYet': 'Nessuna voce wiki',
  'wiki.selectEntry': 'Seleziona una voce dalla barra laterale',
  'wiki.uploadHint': 'Carica audio per generare voci automaticamente, o creane una manualmente',
  'wiki.createEntry': 'Crea Voce Wiki',

  // Wiki form
  'wiki.form.title': 'Titolo *',
  'wiki.form.titlePlaceholder': 'es. Eldrin il Saggio',
  'wiki.form.type': 'Tipo *',
  'wiki.form.content': 'Contenuto *',
  'wiki.form.contentPlaceholder': 'Scrivi il contenuto della voce wiki...',
  'wiki.form.tags': 'Tag (separati da virgola)',
  'wiki.form.tagsPlaceholder': 'es. mago, alleato, magia',

  // Common actions
  'common.save': 'Salva',
  'common.saving': 'Salvataggio...',
  'common.cancel': 'Annulla',
  'common.delete': 'Elimina',
  'common.deleting': 'Eliminazione...',
  'common.edit': 'Modifica',
  'common.close': 'Chiudi',
  'common.confirm': 'Conferma',
  'common.createEntry': 'Crea Voce',

  // Chat
  'chat.title': 'Assistente DM',
  'chat.placeholder': 'Chiedi della campagna o genera contenuti...',
  'chat.emptyTitle': 'Il tuo assistente DM è pronto!',
  'chat.emptySubtitle': 'Chiedi della campagna, o genera PNG, luoghi, incontri e altro.',
  'chat.openPanel': 'Apri chat',
  'chat.closePanel': 'Chiudi chat',
  'chat.you': 'Tu',
  'chat.error': 'Si \u00e8 verificato un errore. Riprova.',

  // Campaigns
  'campaigns.title': 'Le Tue Campagne',
  'campaigns.create': 'Crea Campagna',
  'campaigns.noCampaigns': 'Nessuna campagna',
  'campaigns.createFirst': 'Crea la Tua Prima Campagna',
  'campaigns.audio': 'audio',
  'campaigns.wiki': 'wiki',
  'campaigns.rename': 'Rinomina',

  // Campaign creation
  'campaigns.new.title': 'Crea Nuova Campagna',
  'campaigns.new.name': 'Nome Campagna *',
  'campaigns.new.namePlaceholder': 'La Tana del Drago',
  'campaigns.new.description': 'Descrizione',
  'campaigns.new.descPlaceholder': 'Un\'avventura emozionante tra antiche rovine...',
  'campaigns.new.language': 'Lingua',
  'campaigns.new.languageHint': 'Le voci wiki, i riepiloghi e la chat useranno questa lingua.',

  // Settings modal
  'settings.title': 'Impostazioni Campagna',
  'settings.name': 'Nome Campagna *',
  'settings.description': 'Descrizione',
  'settings.language': 'Lingua',
  'settings.saveChanges': 'Salva Modifiche',
  'settings.dangerZone': 'Zona Pericolosa',
  'settings.dangerText': 'Elimina permanentemente questa campagna e tutti i suoi dati.',
  'settings.deleteCampaign': 'Elimina Campagna',

  // Audio upload modal
  'audio.uploadTitle': 'Carica Registrazione Sessione',
  'audio.uploadSubtitle': 'Carica audio per trascrivere e generare voci wiki automaticamente',
  'audio.dragDrop': 'Trascina un file audio qui',
  'audio.dropHere': 'Rilascia il file qui',
  'audio.orBrowse': 'o clicca per sfogliare',
  'audio.formats': 'MP3, WAV, M4A, OGG (max 100MB)',
  'audio.uploading': 'Caricamento...',
  'audio.creating': 'Creazione record...',
  'audio.processing': 'Elaborazione audio (trascrizione, riepilogo, generazione voci wiki)...',
  'audio.done': 'Fatto! Voci wiki generate.',
  'audio.error': 'Qualcosa \u00e8 andato storto.',
  'audio.waitNote': 'Potrebbe richiedere alcuni minuti per registrazioni lunghe',
  'audio.tryAgain': 'Riprova',
  'audio.uploadAudio': 'Carica Audio',

  // Update wiki modal
  'updateWiki.title': 'Aggiorna Wiki',
  'updateWiki.description': 'Analizza tutti i riepiloghi delle sessioni e crea o aggiorna le voci wiki per personaggi, luoghi, oggetti e altro.',
  'updateWiki.instructions': 'Istruzioni aggiuntive (opzionale)',
  'updateWiki.instructionsPlaceholder': 'es. Concentrati sui nuovi PNG dell\'ultima sessione',
  'updateWiki.generate': 'Genera Wiki',
  'updateWiki.analyzing': 'Analisi sessioni...',
  'updateWiki.done': 'Fatto! Create {created} e aggiornate {updated} voci.',

  // Profile
  'profile.title': 'Profilo',
  'profile.displayName': 'Nome Visualizzato',
  'profile.displayNamePlaceholder': 'Il tuo nome',
  'profile.uiLanguage': 'Lingua Interfaccia',
  'profile.saved': 'Salvato!',
  'profile.memberSince': 'Membro dal',
  'profile.noName': 'Nome non impostato',
}

type TranslationKey = keyof typeof en

const translations: Record<Locale, Record<string, string>> = { en, it }

export function t(locale: Locale, key: TranslationKey | string, params?: Record<string, string | number>): string {
  let value = translations[locale]?.[key] || translations.en[key] || key
  if (params) {
    for (const [k, v] of Object.entries(params)) {
      value = value.replace(`{${k}}`, String(v))
    }
  }
  return value
}
