export type Locale = 'en' | 'it'

const en = {
  // Nav
  'nav.campaigns': 'Campaigns',
  'nav.profile': 'Profile',
  'nav.signOut': 'Sign Out',

  // Sidebar
  'sidebar.allCampaigns': 'All Campaigns',
  'sidebar.upload': 'Upload',
  'sidebar.newPage': 'New Page',
  'sidebar.update': 'Update',
  'sidebar.sessionRecaps': 'Session Recaps',
  'sidebar.campaignWiki': 'Campaign Wiki',
  'sidebar.noEntries': 'No entries yet',
  'sidebar.campaignSettings': 'Campaign settings',

  // Wiki type labels (plural, for sidebar groups)
  'wiki.type.SESSION_RECAP': 'Session Recaps',
  'wiki.type.CHARACTER': 'Characters',
  'wiki.type.LOCATION': 'Locations',
  'wiki.type.EVENT': 'Events',
  'wiki.type.ITEM': 'Items',
  'wiki.type.NPC': 'NPCs',
  'wiki.type.FACTION': 'Factions',
  'wiki.type.LORE': 'Lore',
  'wiki.type.QUEST': 'Quests',
  'wiki.type.OTHER': 'Other',

  // Wiki type labels (singular, for badges)
  'wiki.typeSingle.SESSION_RECAP': 'Session Recap',
  'wiki.typeSingle.CHARACTER': 'Character',
  'wiki.typeSingle.LOCATION': 'Location',
  'wiki.typeSingle.EVENT': 'Event',
  'wiki.typeSingle.ITEM': 'Item',
  'wiki.typeSingle.NPC': 'NPC',
  'wiki.typeSingle.FACTION': 'Faction',
  'wiki.typeSingle.LORE': 'Lore',
  'wiki.typeSingle.QUEST': 'Quest',
  'wiki.typeSingle.OTHER': 'Other',

  // Wiki editor
  'wiki.autoGenerated': 'Auto-generated',
  'wiki.source': 'Source',
  'wiki.relatedEntries': 'Related Entries',
  'wiki.noEntriesYet': 'No wiki entries yet',
  'wiki.selectEntry': 'Select an entry from the sidebar',
  'wiki.uploadHint': 'Upload audio to generate entries automatically, or create one manually',
  'wiki.createEntry': 'Create Wiki Entry',

  // Wiki form
  'wiki.form.title': 'Title *',
  'wiki.form.titlePlaceholder': 'e.g. Eldrin the Wise',
  'wiki.form.type': 'Type *',
  'wiki.form.content': 'Content *',
  'wiki.form.contentPlaceholder': 'Write the wiki entry content...',
  'wiki.form.tags': 'Tags (comma-separated)',
  'wiki.form.tagsPlaceholder': 'e.g. wizard, ally, magic',

  // Common actions
  'common.save': 'Save',
  'common.saving': 'Saving...',
  'common.cancel': 'Cancel',
  'common.delete': 'Delete',
  'common.deleting': 'Deleting...',
  'common.edit': 'Edit',
  'common.close': 'Close',
  'common.confirm': 'Confirm',
  'common.createEntry': 'Create Entry',

  // Chat
  'chat.title': 'DM Companion',
  'chat.placeholder': 'Ask about your campaign or generate content...',
  'chat.emptyTitle': 'Your DM assistant is ready!',
  'chat.emptySubtitle': 'Ask about your campaign, or generate NPCs, locations, encounters, and more.',
  'chat.openPanel': 'Open chat',
  'chat.closePanel': 'Close chat',
  'chat.you': 'You',
  'chat.error': 'Sorry, I encountered an error. Please try again.',

  // Campaigns
  'campaigns.title': 'Your Campaigns',
  'campaigns.create': 'Create Campaign',
  'campaigns.noCampaigns': 'No campaigns yet',
  'campaigns.createFirst': 'Create Your First Campaign',
  'campaigns.audio': 'audio',
  'campaigns.wiki': 'wiki',
  'campaigns.rename': 'Rename',

  // Campaign creation
  'campaigns.new.title': 'Create New Campaign',
  'campaigns.new.name': 'Campaign Name *',
  'campaigns.new.namePlaceholder': 'The Dragon\'s Lair',
  'campaigns.new.description': 'Description',
  'campaigns.new.descPlaceholder': 'A thrilling adventure through ancient ruins...',
  'campaigns.new.language': 'Language',
  'campaigns.new.languageHint': 'Wiki entries, summaries, and chat will use this language.',

  // Settings modal
  'settings.title': 'Campaign Settings',
  'settings.name': 'Campaign Name *',
  'settings.description': 'Description',
  'settings.language': 'Language',
  'settings.saveChanges': 'Save Changes',
  'settings.dangerZone': 'Danger Zone',
  'settings.dangerText': 'Permanently delete this campaign and all its data.',
  'settings.deleteCampaign': 'Delete Campaign',

  // Audio upload modal
  'audio.uploadTitle': 'Upload Session Recording',
  'audio.uploadSubtitle': 'Upload audio to auto-transcribe and generate wiki entries',
  'audio.dragDrop': 'Drag & drop an audio file here',
  'audio.dropHere': 'Drop the file here',
  'audio.orBrowse': 'or click to browse',
  'audio.formats': 'MP3, WAV, M4A, OGG (max 100MB)',
  'audio.uploading': 'Uploading...',
  'audio.creating': 'Creating record...',
  'audio.processing': 'Processing audio (transcribing, summarizing, generating wiki entries)...',
  'audio.done': 'Done! Wiki entries generated.',
  'audio.error': 'Something went wrong.',
  'audio.waitNote': 'This may take a few minutes for longer recordings',
  'audio.tryAgain': 'Try again',
  'audio.uploadAudio': 'Upload Audio',

  // Update wiki modal
  'updateWiki.title': 'Update Wiki',
  'updateWiki.description': 'Analyze all session recaps and create or update wiki entries for characters, locations, items, and more.',
  'updateWiki.instructions': 'Additional instructions (optional)',
  'updateWiki.instructionsPlaceholder': 'e.g. Focus on the new NPCs from the latest session',
  'updateWiki.generate': 'Generate Wiki',
  'updateWiki.analyzing': 'Analyzing sessions...',
  'updateWiki.done': 'Done! Created {created} and updated {updated} entries.',

  // Character sheet
  'characterSheet.boardView': 'Board View',
  'characterSheet.wikiView': 'Wiki View',
  'characterSheet.addPrompt': 'Add an interactive character sheet to track stats, equipment, and spells.',
  'characterSheet.createBlank': 'Create Character Sheet',
  'characterSheet.importPdf': 'Import from PDF',
  'characterSheet.importTitle': 'Import Character Sheet',
  'characterSheet.importSubtitle': 'Upload a D&D Beyond PDF character sheet',
  'characterSheet.importForEntry': 'Import character sheet for {name}',
  'characterSheet.dropHere': 'Drop the PDF here',
  'characterSheet.dragOrClick': 'Drag & drop a character sheet PDF, or click to browse',
  'characterSheet.pdfOnly': 'PDF files only (max 10MB)',
  'characterSheet.uploading': 'Uploading PDF...',
  'characterSheet.processing': 'AI is reading the character sheet...',
  'characterSheet.aiParsing': 'Extracting abilities, equipment, spells, and more',
  'characterSheet.importSuccess': 'Character sheet imported!',
  'characterSheet.redirecting': 'Redirecting to character board...',

  // Common (additions)
  'common.creating': 'Creating...',

  // Profile
  'profile.title': 'Profile',
  'profile.displayName': 'Display Name',
  'profile.displayNamePlaceholder': 'Your name',
  'profile.uiLanguage': 'UI Language',
  'profile.saved': 'Saved!',
  'profile.memberSince': 'Member since',
  'profile.noName': 'No name set',

  // Subscription
  'subscription.title': 'Subscription',
  'subscription.currentPlan': 'Current Plan',
  'subscription.basic': 'Basic',
  'subscription.pro': 'Pro',
  'subscription.free': 'Free',
  'subscription.status': 'Status',
  'subscription.active': 'Active',
  'subscription.canceled': 'Canceled',
  'subscription.pastDue': 'Past Due',
  'subscription.trialing': 'Trialing',
  'subscription.nextBilling': 'Next billing date',
  'subscription.upgradeToPro': 'Upgrade to Pro',
  'subscription.downgradToBasic': 'Downgrade to Basic',
  'subscription.audioUsage': 'Audio transcriptions: {used} / {limit} this month',
  'subscription.audioUsageUnlimited': 'Audio transcriptions: {used} this month (unlimited)',
  'subscription.manageSub': 'Manage Subscription',

  // Pricing
  'pricing.title': 'Choose Your Plan',
  'pricing.subtitle': 'Start free and upgrade when you need more power.',
  'pricing.monthly': 'Monthly',
  'pricing.annual': 'Annual',
  'pricing.perMonth': '/month',
  'pricing.perYear': '/year',
  'pricing.saveBadge': 'Save ~17%',
  'pricing.currentPlan': 'Current Plan',
  'pricing.getStarted': 'Get Started',
  'pricing.subscribe': 'Subscribe',
  'pricing.basicName': 'Basic',
  'pricing.proName': 'Pro',
  'pricing.basicPrice': 'Free',
  'pricing.proMonthly': '$6.99',
  'pricing.proAnnual': '$70',
  'pricing.basicFeature1': '1 campaign',
  'pricing.basicFeature2': '1 audio transcription/month',
  'pricing.basicFeature3': 'Wiki auto-generation',
  'pricing.basicFeature4': 'Character sheets',
  'pricing.basicNoChat': 'No AI chat',
  'pricing.proFeature1': 'Unlimited campaigns',
  'pricing.proFeature2': 'Unlimited audio transcriptions',
  'pricing.proFeature3': 'Wiki auto-generation',
  'pricing.proFeature4': 'Character sheets',
  'pricing.proFeature5': 'AI chat assistant',
  'pricing.proFeature6': 'Priority support',

  // Limits / enforcement
  'limits.campaignLimit': 'You\'ve reached the campaign limit on the Basic plan. Upgrade to Pro for unlimited campaigns.',
  'limits.audioLimit': 'You\'ve used your audio transcription for this month. Upgrade to Pro for unlimited transcriptions.',
  'limits.audioTooLong': 'This audio file exceeds the Basic plan duration limit. Upgrade to Pro for longer recordings.',
  'limits.chatLocked': 'AI Chat is a Pro feature. Upgrade to unlock your campaign assistant.',
  'limits.upgrade': 'Upgrade to Pro',

  // Landing
  'landing.hero': 'Your Ultimate Campaign Management Tool',
  'landing.subtitle': 'For Dungeon Masters & Players',
  'landing.feature1': 'Upload & transcribe session audio',
  'landing.feature2': 'Auto-generate campaign wiki',
  'landing.feature3': 'AI chat with campaign context',
  'landing.getStarted': 'Get Started',
  'landing.viewPricing': 'View Pricing',

  // Nav
  'nav.pricing': 'Pricing',

  // Profile settings & account
  'profile.settings': 'Settings',
  'profile.account': 'Account',
  'profile.dateFormat': 'Date Format',

  // Sidebar sessions/wiki
  'sidebar.sessions': 'Sessions',
  'sidebar.wiki': 'Wiki',
  'sidebar.newSession': 'New Session',
  'sidebar.uploadAudio': 'Upload Audio',
  'sidebar.newWikiPage': 'New Page',
  'sidebar.updateWikiAI': 'Update Wiki (AI)',

  // Session creation
  'session.createTitle': 'Create Session',
  'session.date': 'Session Date',
  'session.title': 'Session Title',
  'session.titlePlaceholder': 'Leave blank to use date as title',
  'session.create': 'Create',
} as const

const it: Record<string, string> = {
  // Nav
  'nav.campaigns': 'Campagne',
  'nav.profile': 'Profilo',
  'nav.signOut': 'Esci',

  // Sidebar
  'sidebar.allCampaigns': 'Tutte le Campagne',
  'sidebar.upload': 'Carica',
  'sidebar.newPage': 'Nuova Pagina',
  'sidebar.update': 'Aggiorna',
  'sidebar.sessionRecaps': 'Riepiloghi Sessione',
  'sidebar.campaignWiki': 'Wiki Campagna',
  'sidebar.noEntries': 'Nessuna voce',
  'sidebar.campaignSettings': 'Impostazioni campagna',

  // Wiki type labels (plural)
  'wiki.type.SESSION_RECAP': 'Riepiloghi Sessione',
  'wiki.type.CHARACTER': 'Personaggi',
  'wiki.type.LOCATION': 'Luoghi',
  'wiki.type.EVENT': 'Eventi',
  'wiki.type.ITEM': 'Oggetti',
  'wiki.type.NPC': 'PNG',
  'wiki.type.FACTION': 'Fazioni',
  'wiki.type.LORE': 'Ambientazione',
  'wiki.type.QUEST': 'Missioni',
  'wiki.type.OTHER': 'Altro',

  // Wiki type labels (singular)
  'wiki.typeSingle.SESSION_RECAP': 'Riepilogo Sessione',
  'wiki.typeSingle.CHARACTER': 'Personaggio',
  'wiki.typeSingle.LOCATION': 'Luogo',
  'wiki.typeSingle.EVENT': 'Evento',
  'wiki.typeSingle.ITEM': 'Oggetto',
  'wiki.typeSingle.NPC': 'PNG',
  'wiki.typeSingle.FACTION': 'Fazione',
  'wiki.typeSingle.LORE': 'Ambientazione',
  'wiki.typeSingle.QUEST': 'Missione',
  'wiki.typeSingle.OTHER': 'Altro',

  // Wiki editor
  'wiki.autoGenerated': 'Auto-generato',
  'wiki.source': 'Fonte',
  'wiki.relatedEntries': 'Voci Correlate',
  'wiki.noEntriesYet': 'Nessuna voce wiki',
  'wiki.selectEntry': 'Seleziona una voce dalla barra laterale',
  'wiki.uploadHint': 'Carica audio per generare voci automaticamente, o creane una manualmente',
  'wiki.createEntry': 'Crea Voce Wiki',

  // Wiki form
  'wiki.form.title': 'Titolo *',
  'wiki.form.titlePlaceholder': 'es. Eldrin il Saggio',
  'wiki.form.type': 'Tipo *',
  'wiki.form.content': 'Contenuto *',
  'wiki.form.contentPlaceholder': 'Scrivi il contenuto della voce wiki...',
  'wiki.form.tags': 'Tag (separati da virgola)',
  'wiki.form.tagsPlaceholder': 'es. mago, alleato, magia',

  // Common actions
  'common.save': 'Salva',
  'common.saving': 'Salvataggio...',
  'common.cancel': 'Annulla',
  'common.delete': 'Elimina',
  'common.deleting': 'Eliminazione...',
  'common.edit': 'Modifica',
  'common.close': 'Chiudi',
  'common.confirm': 'Conferma',
  'common.createEntry': 'Crea Voce',

  // Chat
  'chat.title': 'Assistente DM',
  'chat.placeholder': 'Chiedi della campagna o genera contenuti...',
  'chat.emptyTitle': 'Il tuo assistente DM è pronto!',
  'chat.emptySubtitle': 'Chiedi della campagna, o genera PNG, luoghi, incontri e altro.',
  'chat.openPanel': 'Apri chat',
  'chat.closePanel': 'Chiudi chat',
  'chat.you': 'Tu',
  'chat.error': 'Si \u00e8 verificato un errore. Riprova.',

  // Campaigns
  'campaigns.title': 'Le Tue Campagne',
  'campaigns.create': 'Crea Campagna',
  'campaigns.noCampaigns': 'Nessuna campagna',
  'campaigns.createFirst': 'Crea la Tua Prima Campagna',
  'campaigns.audio': 'audio',
  'campaigns.wiki': 'wiki',
  'campaigns.rename': 'Rinomina',

  // Campaign creation
  'campaigns.new.title': 'Crea Nuova Campagna',
  'campaigns.new.name': 'Nome Campagna *',
  'campaigns.new.namePlaceholder': 'La Tana del Drago',
  'campaigns.new.description': 'Descrizione',
  'campaigns.new.descPlaceholder': 'Un\'avventura emozionante tra antiche rovine...',
  'campaigns.new.language': 'Lingua',
  'campaigns.new.languageHint': 'Le voci wiki, i riepiloghi e la chat useranno questa lingua.',

  // Settings modal
  'settings.title': 'Impostazioni Campagna',
  'settings.name': 'Nome Campagna *',
  'settings.description': 'Descrizione',
  'settings.language': 'Lingua',
  'settings.saveChanges': 'Salva Modifiche',
  'settings.dangerZone': 'Zona Pericolosa',
  'settings.dangerText': 'Elimina permanentemente questa campagna e tutti i suoi dati.',
  'settings.deleteCampaign': 'Elimina Campagna',

  // Audio upload modal
  'audio.uploadTitle': 'Carica Registrazione Sessione',
  'audio.uploadSubtitle': 'Carica audio per trascrivere e generare voci wiki automaticamente',
  'audio.dragDrop': 'Trascina un file audio qui',
  'audio.dropHere': 'Rilascia il file qui',
  'audio.orBrowse': 'o clicca per sfogliare',
  'audio.formats': 'MP3, WAV, M4A, OGG (max 100MB)',
  'audio.uploading': 'Caricamento...',
  'audio.creating': 'Creazione record...',
  'audio.processing': 'Elaborazione audio (trascrizione, riepilogo, generazione voci wiki)...',
  'audio.done': 'Fatto! Voci wiki generate.',
  'audio.error': 'Qualcosa \u00e8 andato storto.',
  'audio.waitNote': 'Potrebbe richiedere alcuni minuti per registrazioni lunghe',
  'audio.tryAgain': 'Riprova',
  'audio.uploadAudio': 'Carica Audio',

  // Update wiki modal
  'updateWiki.title': 'Aggiorna Wiki',
  'updateWiki.description': 'Analizza tutti i riepiloghi delle sessioni e crea o aggiorna le voci wiki per personaggi, luoghi, oggetti e altro.',
  'updateWiki.instructions': 'Istruzioni aggiuntive (opzionale)',
  'updateWiki.instructionsPlaceholder': 'es. Concentrati sui nuovi PNG dell\'ultima sessione',
  'updateWiki.generate': 'Genera Wiki',
  'updateWiki.analyzing': 'Analisi sessioni...',
  'updateWiki.done': 'Fatto! Create {created} e aggiornate {updated} voci.',

  // Character sheet
  'characterSheet.boardView': 'Vista Scheda',
  'characterSheet.wikiView': 'Vista Wiki',
  'characterSheet.addPrompt': 'Aggiungi una scheda personaggio interattiva per monitorare statistiche, equipaggiamento e incantesimi.',
  'characterSheet.createBlank': 'Crea Scheda Personaggio',
  'characterSheet.importPdf': 'Importa da PDF',
  'characterSheet.importTitle': 'Importa Scheda Personaggio',
  'characterSheet.importSubtitle': 'Carica un PDF della scheda personaggio di D&D Beyond',
  'characterSheet.importForEntry': 'Importa scheda personaggio per {name}',
  'characterSheet.dropHere': 'Rilascia il PDF qui',
  'characterSheet.dragOrClick': 'Trascina un PDF della scheda personaggio, o clicca per sfogliare',
  'characterSheet.pdfOnly': 'Solo file PDF (max 10MB)',
  'characterSheet.uploading': 'Caricamento PDF...',
  'characterSheet.processing': 'L\'IA sta leggendo la scheda personaggio...',
  'characterSheet.aiParsing': 'Estrazione abilit\u00e0, equipaggiamento, incantesimi e altro',
  'characterSheet.importSuccess': 'Scheda personaggio importata!',
  'characterSheet.redirecting': 'Reindirizzamento alla scheda...',

  // Common (additions)
  'common.creating': 'Creazione...',

  // Profile
  'profile.title': 'Profilo',
  'profile.displayName': 'Nome Visualizzato',
  'profile.displayNamePlaceholder': 'Il tuo nome',
  'profile.uiLanguage': 'Lingua Interfaccia',
  'profile.saved': 'Salvato!',
  'profile.memberSince': 'Membro dal',
  'profile.noName': 'Nome non impostato',

  // Subscription
  'subscription.title': 'Abbonamento',
  'subscription.currentPlan': 'Piano Attuale',
  'subscription.basic': 'Base',
  'subscription.pro': 'Pro',
  'subscription.free': 'Gratuito',
  'subscription.status': 'Stato',
  'subscription.active': 'Attivo',
  'subscription.canceled': 'Cancellato',
  'subscription.pastDue': 'Pagamento in ritardo',
  'subscription.trialing': 'Periodo di prova',
  'subscription.nextBilling': 'Prossima fatturazione',
  'subscription.upgradeToPro': 'Passa a Pro',
  'subscription.downgradToBasic': 'Passa a Base',
  'subscription.audioUsage': 'Trascrizioni audio: {used} / {limit} questo mese',
  'subscription.audioUsageUnlimited': 'Trascrizioni audio: {used} questo mese (illimitate)',
  'subscription.manageSub': 'Gestisci Abbonamento',

  // Pricing
  'pricing.title': 'Scegli il Tuo Piano',
  'pricing.subtitle': 'Inizia gratis e aggiorna quando hai bisogno di pi\u00f9 potenza.',
  'pricing.monthly': 'Mensile',
  'pricing.annual': 'Annuale',
  'pricing.perMonth': '/mese',
  'pricing.perYear': '/anno',
  'pricing.saveBadge': 'Risparmia ~17%',
  'pricing.currentPlan': 'Piano Attuale',
  'pricing.getStarted': 'Inizia',
  'pricing.subscribe': 'Abbonati',
  'pricing.basicName': 'Base',
  'pricing.proName': 'Pro',
  'pricing.basicPrice': 'Gratuito',
  'pricing.proMonthly': '\u20ac6,99',
  'pricing.proAnnual': '\u20ac70',
  'pricing.basicFeature1': '1 campagna',
  'pricing.basicFeature2': '1 trascrizione audio/mese',
  'pricing.basicFeature3': 'Generazione wiki automatica',
  'pricing.basicFeature4': 'Schede personaggio',
  'pricing.basicNoChat': 'Nessuna chat IA',
  'pricing.proFeature1': 'Campagne illimitate',
  'pricing.proFeature2': 'Trascrizioni audio illimitate',
  'pricing.proFeature3': 'Generazione wiki automatica',
  'pricing.proFeature4': 'Schede personaggio',
  'pricing.proFeature5': 'Assistente chat IA',
  'pricing.proFeature6': 'Supporto prioritario',

  // Limits / enforcement
  'limits.campaignLimit': 'Hai raggiunto il limite di campagne del piano Base. Passa a Pro per campagne illimitate.',
  'limits.audioLimit': 'Hai usato la tua trascrizione audio per questo mese. Passa a Pro per trascrizioni illimitate.',
  'limits.audioTooLong': 'Questo file audio supera il limite di durata del piano Base. Passa a Pro per registrazioni pi\u00f9 lunghe.',
  'limits.chatLocked': 'La chat IA \u00e8 una funzione Pro. Passa a Pro per sbloccare l\'assistente della campagna.',
  'limits.upgrade': 'Passa a Pro',

  // Landing
  'landing.hero': 'Il Tuo Strumento Definitivo per la Gestione delle Campagne',
  'landing.subtitle': 'Per Dungeon Master e Giocatori',
  'landing.feature1': 'Carica e trascrivi l\'audio delle sessioni',
  'landing.feature2': 'Genera automaticamente la wiki della campagna',
  'landing.feature3': 'Chat IA con contesto della campagna',
  'landing.getStarted': 'Inizia',
  'landing.viewPricing': 'Vedi i Prezzi',

  // Nav
  'nav.pricing': 'Prezzi',

  // Profile settings & account
  'profile.settings': 'Impostazioni',
  'profile.account': 'Account',
  'profile.dateFormat': 'Formato Data',

  // Sidebar sessions/wiki
  'sidebar.sessions': 'Sessioni',
  'sidebar.wiki': 'Wiki',
  'sidebar.newSession': 'Nuova Sessione',
  'sidebar.uploadAudio': 'Carica Audio',
  'sidebar.newWikiPage': 'Nuova Pagina',
  'sidebar.updateWikiAI': 'Aggiorna Wiki (IA)',

  // Session creation
  'session.createTitle': 'Crea Sessione',
  'session.date': 'Data Sessione',
  'session.title': 'Titolo Sessione',
  'session.titlePlaceholder': 'Lascia vuoto per usare la data come titolo',
  'session.create': 'Crea',
}

type TranslationKey = keyof typeof en

const translations: Record<Locale, Record<string, string>> = { en, it }

export function t(locale: Locale, key: TranslationKey | string, params?: Record<string, string | number>): string {
  let value = translations[locale]?.[key] || translations.en[key] || key
  if (params) {
    for (const [k, v] of Object.entries(params)) {
      value = value.replace(`{${k}}`, String(v))
    }
  }
  return value
}
