'use server'

import { revalidatePath } from 'next/cache'
import { prisma } from '@/lib/db'
import { WikiEntryType } from '@prisma/client'

function slugify(text: string): string {
  return text
    .toLowerCase()
    .replace(/[^a-z0-9]+/g, '-')
    .replace(/^-+|-+$/g, '')
}

export async function createWikiEntry(
  campaignId: string,
  userId: string,
  data: {
    title: string
    type: WikiEntryType
    content: string
    excerpt?: string
    tags?: string[]
  }
) {
  const campaign = await prisma.campaign.findFirst({
    where: { id: campaignId, ownerId: userId },
  })

  if (!campaign) {
    throw new Error('Campaign not found or unauthorized')
  }

  const baseSlug = slugify(data.title)
  let slug = baseSlug
  let counter = 1

  // Ensure unique slug
  while (await prisma.wikiEntry.findUnique({ where: { campaignId_slug: { campaignId, slug } } })) {
    slug = `${baseSlug}-${counter++}`
  }

  const entry = await prisma.wikiEntry.create({
    data: {
      title: data.title,
      slug,
      type: data.type,
      content: data.content,
      excerpt: data.excerpt || data.content.slice(0, 200),
      tags: data.tags || [],
      isAutoGenerated: false,
      campaignId,
    },
  })

  revalidatePath(`/campaigns/${campaignId}/wiki`)
  return entry
}

export async function getWikiEntries(
  campaignId: string,
  userId: string,
  filters?: {
    type?: WikiEntryType
    search?: string
    tags?: string[]
  }
) {
  // Verify ownership
  const campaign = await prisma.campaign.findFirst({
    where: { id: campaignId, ownerId: userId },
  })

  if (!campaign) {
    throw new Error('Campaign not found or unauthorized')
  }

  const where: any = { campaignId }

  if (filters?.type) {
    where.type = filters.type
  }

  if (filters?.search) {
    where.OR = [
      { title: { contains: filters.search, mode: 'insensitive' } },
      { content: { contains: filters.search, mode: 'insensitive' } },
      { excerpt: { contains: filters.search, mode: 'insensitive' } },
    ]
  }

  if (filters?.tags && filters.tags.length > 0) {
    where.tags = { hasSome: filters.tags }
  }

  return await prisma.wikiEntry.findMany({
    where,
    orderBy: { createdAt: 'desc' },
    include: {
      audioFile: {
        select: {
          id: true,
          filename: true,
        },
      },
    },
  })
}

export async function getWikiEntry(entryId: string, userId: string) {
  const entry = await prisma.wikiEntry.findUnique({
    where: { id: entryId },
    include: {
      campaign: true,
      audioFile: {
        select: {
          id: true,
          filename: true,
        },
      },
      children: true,
    },
  })

  if (!entry || entry.campaign.ownerId !== userId) {
    throw new Error('Wiki entry not found or unauthorized')
  }

  return entry
}

export async function searchWikiEntries(
  campaignId: string,
  userId: string,
  query: string
) {
  // Verify ownership
  const campaign = await prisma.campaign.findFirst({
    where: { id: campaignId, ownerId: userId },
  })

  if (!campaign) {
    throw new Error('Campaign not found or unauthorized')
  }

  return await prisma.wikiEntry.findMany({
    where: {
      campaignId,
      OR: [
        { title: { contains: query, mode: 'insensitive' } },
        { content: { contains: query, mode: 'insensitive' } },
        { excerpt: { contains: query, mode: 'insensitive' } },
        { tags: { has: query.toLowerCase() } },
      ],
    },
    orderBy: { createdAt: 'desc' },
    take: 20,
  })
}

export async function updateWikiEntry(
  entryId: string,
  userId: string,
  data: {
    title?: string
    content?: string
    type?: WikiEntryType
    tags?: string[]
  }
) {
  const entry = await prisma.wikiEntry.findUnique({
    where: { id: entryId },
    include: { campaign: { select: { ownerId: true, id: true } } },
  })

  if (!entry || entry.campaign.ownerId !== userId) {
    throw new Error('Wiki entry not found or unauthorized')
  }

  const updated = await prisma.wikiEntry.update({
    where: { id: entryId },
    data: {
      ...(data.title !== undefined && { title: data.title }),
      ...(data.content !== undefined && { content: data.content, excerpt: data.content.slice(0, 200) }),
      ...(data.type !== undefined && { type: data.type }),
      ...(data.tags !== undefined && { tags: data.tags }),
    },
  })

  revalidatePath(`/campaigns/${entry.campaign.id}`)
  return updated
}

export async function deleteWikiEntry(entryId: string, userId: string) {
  const entry = await prisma.wikiEntry.findUnique({
    where: { id: entryId },
    include: { campaign: { select: { ownerId: true, id: true } } },
  })

  if (!entry || entry.campaign.ownerId !== userId) {
    throw new Error('Wiki entry not found or unauthorized')
  }

  await prisma.wikiEntry.delete({ where: { id: entryId } })

  revalidatePath(`/campaigns/${entry.campaign.id}`)
}

export async function getWikiTree(campaignId: string, userId: string) {
  const campaign = await prisma.campaign.findFirst({
    where: { id: campaignId, ownerId: userId },
  })

  if (!campaign) {
    throw new Error('Campaign not found or unauthorized')
  }

  return await prisma.wikiEntry.findMany({
    where: { campaignId },
    select: {
      id: true,
      title: true,
      slug: true,
      type: true,
      parentId: true,
      createdAt: true,
    },
    orderBy: [{ type: 'asc' }, { createdAt: 'desc' }],
  })
}

export async function getWikiEntriesByType(
  campaignId: string,
  userId: string
) {
  // Verify ownership
  const campaign = await prisma.campaign.findFirst({
    where: { id: campaignId, ownerId: userId },
  })

  if (!campaign) {
    throw new Error('Campaign not found or unauthorized')
  }

  const entries = await prisma.wikiEntry.groupBy({
    by: ['type'],
    where: { campaignId },
    _count: true,
  })

  return entries
}
